### ISSUE TITLE
Emacs : Symbol's function definition is void: decf

### ISSUE THREAD

**Issue by brockmdean** [jlongster/prettier#110]
I am using emacs (24.3.1) and I added the before save hook from the readme.md. When I run M-x prettier I get this error  : 

    save-current-buffer: Symbol's function definition is void: decf

this symbol (decf) is on line 129 of prettier-js.el.

running from the command line works properly. 

Dean

**Comment by jlongster** [comment]
That's very weird. I'm on 25.1.1. `decf` is defined in `cl.el` which has this at the top:

```
;;; cl.el --- Compatibility aliases for the old CL library.  -*- lexical-binding: t -*-
```

It looks like `decf` is the same as `(setq foo (- foo 1))`. Would be willing to try to change that line, see if it works, and open a PR if so?

**Comment by brockmdean** [comment]
yes, ill tryit out.

**Comment by brockmdean** [comment]
well,
I tried 2 different modifications, but I got an error either way, wrong argument type.
the original line 
   (decf line-offset len)
version 1
(setq line-offset (- line-offset len))
version 2 
(setq line-offset (- line-offset 1 ) len)

also there is an incf that is undefined as well, and tried replacing it with (setq line-offset (line-offset +1) with no success. 

also I looked around for cl.el, but I dont have it and according to this 

https://www.emacswiki.org/emacs/CommonLispForEmacs 

cl.el has been replaced by cl-lib.el, which i also don't have. 

Dean

**Comment by jlongster** [comment]
We need to find someone who know Emacs Lisp better than I do. I will try to use your version of Emacs at some point. Unfortunately I'm not sure what to tell you off-hand right now.

**Comment by brockmdean** [comment]
once stdin works, it will be pretty easy to use M-| to replace the current buffer with the output from prettier

**Comment by brockmdean** [comment]
I tried it out and the fixe #138 fixes this for me .
