### ISSUE TITLE
Add list of plugins to Readme.md

### ISSUE THREAD

**Issue by colek42** [jlongster/prettier#115]

**Comment by vramana** [comment]
Do you mean editor plugins?

**Comment by colek42** [comment]
Yes, it would be nice to reference some of the editor plugins that people have built.  
ex:  https://github.com/esbenp/prettier-vscode

**Comment by jlongster** [comment]
We already have atom/emacs/vim in there. We should probably group them into a single "Editors" section. For vscode, as far as I know it's still stabilizing and multiple people started working on one so I want to make sure that it works well before linking to it.

**Comment by jlongster** [comment]
Closing as we already have a list of of current plugins and authors can open PRs to add themselves (I reached out to the vscode authors). I may reformat the editor list to be clearer soon.
