### ISSUE TITLE
Project Potential

### ISSUE THREAD

**Issue by ericclemmons** [jlongster/prettier#129]
This is purely my opinion, but I wanted to offer up what I see as future value in this project (and potentially others)...

- Even with linters like `standard`, JavaScript's landscape is far from _standard_.
- AirBnB's `eslint` config is quite popular, but is still customized based on preference.
- With linters, **the burden to write "pretty" code is entirely on the developer** to fix & internalize.
- Projects like [parinfer](https://shaunlebron.github.io/parinfer/) are **huge** for Lisp/ClojureScript development, as **the developer focuses on functionality, not aesthetics**.
- There is still usefulness in linters, primarily with undefined variables, & potentially broken code (syntax errors).
- However, I strongly believe that **`prettier` (or some future project) that behaves like `parinfer` to real-time format JS code will render the majority of stylistic bike-shedding moot**, in a similar way that `create-react-app` has simplified application development and removed a burden from user-space.

So, I think this is an awesome project with a ton of potential.  Personally, I'd love to have the `parinfer` of JS as I code and just not give a crap about who's style to use, because it would no longer require any involvement on my part.

**Comment by ericclemmons** [comment]
Closing  because this isn't actionable. But I didn't want to tweet storm it ;)

**Comment by brunolemos** [comment]
> But even more than that: because formatting is completely automatic, you can easily separate the stored representation of text and what's in your editor. You can open a file and immediately it format it as you like, and before committing make sure it's formatted back. These transformations are guaranteed to be consistent if the code is always parsed to the same AST.
> 
> The Reason community jokes that they could even have an S-expression syntax for Reason and it would just be another transform. You could theoretically have a completely different syntax for JS and as long as you have a parser that parses it to the same babylon AST.

😲  that would be huge!

**Comment by josephfrazier** [comment]
> But even more than that: because formatting is completely automatic, you can easily separate the stored representation of text and what's in your editor. You can open a file and immediately it format it as you like, and before committing make sure it's formatted back. These transformations are guaranteed to be consistent if the code is always parsed to the same AST.

For projects that use prettier, developers who prefer a different prettier config could configure git [smudge/clean filters](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#filters_a) to do this for them, without having to involve editors. For example, putting this into `.git/config`:

```
[filter "prettier"]
	clean = prettier --stdin --no-semi --single-quote
	smudge = prettier --stdin
```

and putting this into `.git/info/attributes`:

```
*.js filter=prettier
```

makes it so that files are checked into the repository with single quotes and without semicolons, but are checked out onto the disk with double quotes and semicolons.
