### ISSUE TITLE
Arrow functions which return object literals unnecessarily break

### ISSUE THREAD

**Issue by mstijak** [jlongster/prettier#130]
I tried this example:
```
export const setProp = y => ({
  ...y,
  a: 'very, very, very long text'
});

export const log = y => {
  console.log('very, very, very long text')
};
```
For printWidth: 40, prettier outputs:
```
export const setProp = y =>
  ({
    ...y,
    a: "very, very, very long text"
  });

export const log = y => {
  console.log(
    "very, very, very long text"
  );
};
```

I'm not sure if it is intentional, but it seems that brackets break the last function argument rule. I would prefer:
```
export const setProp = y => ({
  ...y,
  a: "very, very, very long text"
});

export const log = y => {
  console.log(
    "very, very, very long text"
  );
};
```
[Example](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20const%20setProp%20%3D%20y%20%3D%3E%20(%7B%5Cn%20%20...y%2C%5Cn%20%20a%3A%20'very%2C%20very%2C%20very%20long%20text'%5Cn%7D)%3B%5Cn%5Cnexport%20const%20log%20%3D%20y%20%3D%3E%20%7B%5Cn%20%20console.log('very%2C%20very%2C%20very%20long%20text')%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A40%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D)

**Comment by jlongster** [comment]
Yes we need to fix this, I think this might be included in another issue but I'm not sure. This is a regression from another commit. Will fix soon.

**Comment by BLamy** [comment]
I'm sure you're probably up to your neck with edge cases but heres another example of this. 

![image](https://cloud.githubusercontent.com/assets/324928/21895463/d54cd6d6-d8b0-11e6-839a-8c278bf53c65.png)
![image](https://cloud.githubusercontent.com/assets/324928/21895471/dbe1eaae-d8b0-11e6-98a3-db1bd2f92ac3.png)

Love the formatter though. Will definitely start using it at work once it's had a little more time to mature.
