### ISSUE TITLE
Various comments issues on Nuclide

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#135]
- [x] Function is expanded even though it doesn't fit 80 column

![image](https://cloud.githubusercontent.com/assets/197597/22086657/b646dcfe-dd8e-11e6-80a6-3a81636c08d5.png)

- [x] Interesting way to insert a comment (the TODO one)

![image](https://cloud.githubusercontent.com/assets/197597/21871167/33706224-d815-11e6-89b7-169f09d04e56.png)

- [x] Should be consistent where comments are put, either before (preferred) or after, but a mix of both is confusing

![image](https://cloud.githubusercontent.com/assets/197597/21871717/df525a2c-d818-11e6-85ee-32ce5bc29a54.png)

- [ ] It decided to stop trying to pretty print!? Maybe related to the comment

![image](https://cloud.githubusercontent.com/assets/197597/21871955/65158502-d81a-11e6-91ca-d1d01f1d3611.png)

- [ ] Missing one level of indent. Maybe related to the comment

![image](https://cloud.githubusercontent.com/assets/197597/21872033/e4081c58-d81a-11e6-97f3-e770e7e1d867.png)

- [x] It moved the comment to somewhere completely unrelated

![image](https://cloud.githubusercontent.com/assets/197597/21872065/22e329cc-d81b-11e6-94dc-6e3e81512aa7.png)

- [x] I think it's fine to go > 80 columns if comments are involved. It is weird having it pushed to the next line

![image](https://cloud.githubusercontent.com/assets/197597/21871436/f7935660-d816-11e6-9ac9-5906b43d2ea3.png)

- [ ] Comments have disappeared!!!

![image](https://cloud.githubusercontent.com/assets/197597/21871697/b63b4496-d818-11e6-8a31-2c351a25d271.png)

- [ ] For some reason it indented by 4 instead of 2

![image](https://cloud.githubusercontent.com/assets/197597/21871685/a610e972-d818-11e6-9184-3dda5c497fae.png)

- [x] it should either break all the arguments or go > 80 column, it's really weird to break like this. Related to comments

![image](https://cloud.githubusercontent.com/assets/197597/21871839/a7e214d2-d819-11e6-8bbe-1b4825939f86.png)

- [x] eslint-disable-line comment no longer works

![image](https://cloud.githubusercontent.com/assets/197597/21871818/87b05746-d819-11e6-890c-5344b77cd8e3.png)

**Comment by jlongster** [comment]
Most of these are fixed. I'm closing this one when my PR lands and we can split out the one or two things not fixed in separate issues.

**Comment by jlongster** [comment]
See above PR
