### ISSUE TITLE
Add brackets when wrapping 1-line bracketless ifs

### ISSUE THREAD

**Issue by pornel** [jlongster/prettier#14]
That might be a personal preference, but I try to never use [goto fail](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/)-style `if`s.

This is OK:

```js
if (err) return err;
```

This is not (but that's how prettier currently wraps):

```js
if (err)
    return err;
```

so I'd prefer if wrapping added curly braces like this:

```js
if (err) {
   return err;
}
```

**Comment by wmertens** [comment]
I always use `if (err) {return err}` for these short escape clauses. I like to always have `{}` for safety.

Maybe the rule can be that if the body is small enough, it can go on the same line?

**Comment by jlongster** [comment]
I think we can make it so if you don't use brackets, it will try to put the single expression on the same line. The formatter always prints brackets across lines so we can't do the style above. I'd say if you want it on the same line don't use brackets.

**Comment by adamdonahue** [comment]
I think it shouldn't try to put a single line if on one line.  Some styles prefer:

```javascript
if (cond)
    doSomething();
```

This should probably just be an option.
