### ISSUE TITLE
Nuclide run-through #3

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#140]
- [x] Trailing space for types

![image](https://cloud.githubusercontent.com/assets/197597/21871134/029fb87a-d815-11e6-8894-33713ac3abf8.png)

- [x] Trailing whitespace for argument type

![image](https://cloud.githubusercontent.com/assets/197597/21871598/02d6d3d4-d818-11e6-92f8-e91718542c68.png)

- [ ] `{}` should be on their own line

![image](https://cloud.githubusercontent.com/assets/197597/21871214/7859db0e-d815-11e6-9160-075bc739505a.png)

- [ ] Doesn't break #146

![image](https://cloud.githubusercontent.com/assets/197597/21871312/34a29508-d816-11e6-9467-e543c59d4be4.png)

- [x] Missing parenthesis for await #164

![image](https://cloud.githubusercontent.com/assets/197597/21871350/7b94df8e-d816-11e6-93d0-5f89843b667b.png)

- [x] We have an unwritten rule where we use `"` if it means not adding an escape. Not sure about this one but this may be nice.

![image](https://cloud.githubusercontent.com/assets/197597/21871367/8aace9c6-d816-11e6-8036-1263b4e08c8e.png)

- [x] Special case `for (;;) {`

![image](https://cloud.githubusercontent.com/assets/197597/21871520/82681212-d817-11e6-830a-26a443dc743f.png)

- [x] Should hardcode `\0` to stay as is, `\u0000` while valid is weird.

![image](https://cloud.githubusercontent.com/assets/197597/21871743/0789f072-d819-11e6-8a3c-ec348833df2b.png)

- [x] Weird insertion of commas

![image](https://cloud.githubusercontent.com/assets/197597/21871878/f3825c76-d819-11e6-8176-2c9551b487cb.png)

- [ ] Overly aggressive at breaking #130 

![image](https://cloud.githubusercontent.com/assets/197597/21872007/bf339e16-d81a-11e6-8b12-41e0550f8cfe.png)

**Comment by knowbody** [comment]
I've got one here as well, probably similar to the last one from @vjeux's comment above:

![image](https://cloud.githubusercontent.com/assets/3802023/21929614/8a76ec12-d989-11e6-8e77-8449bc445d63.png)

**Comment by vjeux** [comment]
#130 is tracking the issue you mention @knowbody

**Comment by knowbody** [comment]
thank you @vjeux

**Comment by vjeux** [comment]
Closing this one, most of those are now either done or have separate issues.
