### ISSUE TITLE
prettier does not recognize globstar pattern

### ISSUE THREAD

**Issue by tnhu** [jlongster/prettier#145]
I'm on 0.0.5.

```
./e2e
  |- settings.js
  |- request.js
  |- signin.spec.js
```

This works:

```
$ prettier e2e/*.js --write --single-quote

e2e/request.js
e2e/settings.js
e2e/signin.spec.js
```

This does not:

```sh
$ prettier e2e/**/*.js --write --single-quote

e2e/**/*.js
Unable to read file: e2e/**/*.js
Error: ENOENT: no such file or directory, open 'e2e/**/*.js'
```

glob module works just fine:

```js
require("glob")("e2e/**/*.js", (err, files) => console.log(files));

[ 'e2e/request.js', 'e2e/settings.js', 'e2e/signin.spec.js' ]
```

**Comment by demoneaux** [comment]
Currently prettier isn't using the `glob` module, it is dependent on the shell to expand the glob pattern and pass it a series of filenames.

**Comment by jlongster** [comment]
Yeah, you must not be using zsh or a shell that supports it. We should probably support globbing ourselves and provide more advanced options for formatting directories.

**Comment by jlongster** [comment]
If someone wants to revamp the cli to take a pattern, feel free to. It should be backwards compatible. Instead of taking in each filename as a raw string, pass it to glob first or something and accumulate the list of files.

**Comment by brunolemos** [comment]
I'm also having issues with this. After running `prettier --write src/**/*.js`, it found:

```
./src/a/a.js
./src/a/b.js
```

The correct behaviour would be to find all nested folders, but didn't:
```
./src/index.js
./src/a/a.js
./src/b/b.js
./src/cc/cc/c.js
./src/dd/dd/dd/d.js
```

The current workaround is to run the cli command multiple times:
`prettier --write src/*.js`
`prettier --write src/**/*.js`
`prettier --write src/**/**/*.js`
`prettier --write src/**/**/**/*.js`
