### ISSUE TITLE
[MemberExpression] Fails to keep within printWidth when first method call has a parameter

### ISSUE THREAD

**Issue by karl** [jlongster/prettier#146]
This one seems best explained by an example!

Input:

```
foo(() => {
  foo(() => {
    foo(() => {
      
      // Formats incorrectly - longer than printWidth
      bar(a).foo({
        label: 'Field',
        name: 'label',
        value: LABEL,
        options: STRING_FIELDS,
      });

      // Formats correctly
      bar().foo({
        label: 'Field',
        name: 'label',
        value: LABEL,
        options: STRING_FIELDS,
      });

    });
  });
});
```

Output:

```
foo(() => {
  foo(() => {
    foo(() => {
      // Formats incorrectly - longer than printWidth
      bar(
        a
      ).foo({ label: "Field", name: "label", value: LABEL, options: STRING_FIELDS });

      // Formats correctly
      bar().foo({
        label: "Field",
        name: "label",
        value: LABEL,
        options: STRING_FIELDS
      });
    });
  });
});
```

I would have expected both chunks of code to have been formatted in the same manner as the second chunk.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22foo(()%20%3D%3E%20%7B%5Cn%20%20foo(()%20%3D%3E%20%7B%5Cn%20%20%20%20foo(()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%2F%2F%20Formats%20incorrectly%20-%20longer%20than%20printWidth%5Cn%20%20%20%20%20%20bar(a).foo(%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Field'%2C%5Cn%20%20%20%20%20%20%20%20name%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20value%3A%20LABEL%2C%5Cn%20%20%20%20%20%20%20%20options%3A%20STRING_FIELDS%2C%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20%20%20%2F%2F%20Formats%20correctly%5Cn%20%20%20%20%20%20bar().foo(%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Field'%2C%5Cn%20%20%20%20%20%20%20%20name%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20value%3A%20LABEL%2C%5Cn%20%20%20%20%20%20%20%20options%3A%20STRING_FIELDS%2C%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D)%3B%5Cn%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by vjeux** [comment]
#268 is the same issue. Let's condensate the two into a single issue.
