### ISSUE TITLE
Trailing comma adds a comma to function parameters as well

### ISSUE THREAD

**Issue by luisherranz** [jlongster/prettier#152]
If `Training comma` is activated, it adds a comma to the function parameters as well.

For example:

```javascript
someFunction(somethingreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylong);
```

gets converted to:

```javascript
someFunction(
  somethingreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylong,
);
```
which introduces a comma at the end and breaks the code.

I love the project by the way, congrats ☺️

**Comment by vramana** [comment]
This is the expected behaviour. You need add babel plugin to deal with this. function parameters will allow comma in the upcoming edition of ECMAScript.

**Comment by luisherranz** [comment]
Uhm... I see. 

Although I use it most of the time for ES6, sometimes I have files in ES5, like for example webpack.config files.

I think that if the output of `prettier` is not compatible with ES5 even if there is only ES5 code in the file, it will lose some of its utility.

**Comment by vramana** [comment]
https://github.com/jlongster/prettier/issues/68 You can debate here.

**Comment by luisherranz** [comment]
Yep, I just found that as well. Thanks ☺️

**Comment by brainsandspace** [comment]
Just came across this issue myself. For anyone in the future struggling with this problem, one short-term solution you can do is a regex find replace.

Search for ` ,(\n\s*)\) ` and replace with `$1)`.

This is what I ended up doing for a project that I didn't feel like setting up babel/webpack for, but still wanted to use prettier.

**Comment by hawkrives** [comment]
You can also pass the `--trailing-comma` argument to the prettier cli. Try `--trailing-comma es5` or `--trailing-comma none`, depending on what you want.

**Comment by hawkrives** [comment]
(that last was directed @brainsandspace)
