### ISSUE TITLE
.prettierrc

### ISSUE THREAD

**Issue by BLamy** [jlongster/prettier#154]
I searched and didn't really see anything for this but as prettier gets more configuration options it would be ideal to be able to configure it on a per project basis. 

For instance, some projects use trailing commas others don't. Some projects don't use semicolons others may want automatic semicolon insertion.

Seeing a .prettierrc file in the project is probably a good tip off that they expect all code to be formatted with prettier.

**Comment by hzoo** [comment]
https://github.com/jlongster/prettier/issues/40 can cover this in a way if you haven't seen

**Comment by vramana** [comment]
@jlongster has confirmed that he is not interested in adding configuration files to prettier. He will soon add FAQ document for this.

**Comment by brunolemos** [comment]
I may be missing something too.
I agree with the not-too-many-config approach, but if this lib already supports some options, why not support a `.prettierrc` file too? It's not asking to add more configuration, just an easier way to read them.

---
Where I'm coming from:
I've put the prettier configs in the `vscode` `settings.json`.
Later, I run the cli command and did not pass the options in the cli, so it of course changed all my files back to the defaults. I was so used to eslint, babel, etc, looking at config files that I didn't realized the cli command would not use it. :)

**Comment by rattrayalex-stripe** [comment]
Prettier now has a configuration file.

Docs: https://github.com/prettier/prettier/blob/master/README.md#configuration-file
Release notes: https://github.com/prettier/prettier/releases/tag/1.6.0
