### ISSUE TITLE
polymer elements

### ISSUE THREAD

**Issue by davidmaxwaterman** [jlongster/prettier#158]
I wonder if there is any hope for supporting polymer elements, which are html files that include all of html, css and javascript. I imagine it might be easy enough to use the tool in the PSK's gulp pipeline to format the javascript alone (since it splits everything into separate languages), but it'd be nice to have it work in our editors.

**Comment by jlongster** [comment]
We'll never be able to support some kind of mixed mode unless babylon or flow parsers give me a single JS AST. I don't see this happening any time soon, sorry. Mixed mode is very hard to get right, like JSX, but JSX has enough context and is built to be embedded in JS that it's still easier.

You're looking for a HTML and CSS formatter as well which this is not.

**Comment by jlongster** [comment]
(Although, a quick followup: eventually we'll probably have cool editor integration where you can easily format parts of a file. So you could at least easily format the JS in the file, even if it can't format the HTML/CSS)

**Comment by matthewp** [comment]
Maybe I'm misunderstanding @davidmaxwaterman's request here, but I don't think he is asking that HTML formatting be part of prettier, just that inline scripts have their JavaScript be formatted. You could use a tool like cheerio to create an HTML ast and just find the scripts and prettify those, without touching the HTML.  Are you concerned that this might be a slippery slope or... ?

**Comment by jlongster** [comment]
@matthewp I definitely wouldn't want that to be in a core, that would be another tool on top of this. Those kinds of layers will change frequently and people want different things so it's best to the stability of this project to stay more focused and all editor integration to work with our API to do different things.

(And yes, I misunderstood the original question, thought he was asking for us to format the whole file)

**Comment by matthewp** [comment]
That's cool, I understand that. As long as prettier's JS api can take a string it should be easy enough to build something like an HTML formatter and use prettier under the hood.

**Comment by web-padawan** [comment]
Created #3767 as it was suggested to file separate issue apart from the Vue support.
