### ISSUE TITLE
Adds extra comma

### ISSUE THREAD

**Issue by AaronVasquez** [jlongster/prettier#160]
Seems to be adding an extra comma. Might be a fat arrow compatibility issue?

```javascript
request(
    {
      url: fetchUrl,
      method: 'GET',
    },
    (err, res, body) => {
      // Do whatever.
    }, // <== This comma is added.
  );
```

**Comment by AaronVasquez** [comment]
Also, I have trailing comma turned on.

**Comment by jlongster** [comment]
See https://github.com/jlongster/prettier/issues/68. Right now trailing commas also put them in function args because that is soon going to be a JS standard and there is a babel extension to strip them out. But we plan on making `trailingCommas` a tiered config option.
