### ISSUE TITLE
Prints out syntax error

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#162]
```js
  it('it should only display attributes that are specified as an argument', () => {
```

This gets formated into 
```js
  it('it should only display attributes that are specified as an argument', (
    ,
  ) =>
```

running v0.0.5
Using the atom plugin with the following settings
![image](https://cloud.githubusercontent.com/assets/4514159/21929059/58b31686-d986-11e6-82f6-f1457f889d9b.png)

**Comment by vramana** [comment]
Closing this issue, it's already traked at #118
