### ISSUE TITLE
Handle block scoped alignement formatting

### ISSUE THREAD

**Issue by evanliomain** [jlongster/prettier#188]
Add an option (or in default behavior) to handle block scoped alignement.

# Object keys:

## BAD
```javascript
let test;

test = {
  property1: 'value1',
  property10: 'value10',
  property100: 'value100',

  propertyInAnotherBlock: 'valueInAnotherBlock',
  propertyWithNestedObject: {
    nestedProperty: 1
  },
  anotherPropertyWithNestedObject: {
    nestedProperty: 1
  }
}
```

## GOOD
```javascript
let test;

test = {
  property1   : 'value1',
  property10  : 'value10',
  property100 : 'value100',

  propertyInAnotherBlock   : 'valueInAnotherBlock',
  propertyWithNestedObject : {
    nestedProperty : 1
  },
  anotherPropertyWithNestedObject : {
    nestedProperty : 1
  }
}
```

# Variables assignement:

## BAD
```javascript
let var1,
    var10 = 'first10',
    var100 = 'first100',

    varInAnotherBlock = 'valueInAnotherBlock';

var1 = 'value1';
var10 = 'value10';
var100 = 'value100';

varInAnotherBlock = 'valueInAnotherBlock';
```

## GOOD
```javascript
let var1,
    var10  = 'first10',
    var100 = 'first100',

    varInAnotherBlock = 'valueInAnotherBlock';

var1   = 'value1';
var10  = 'value10';
var100 = 'value100';

varInAnotherBlock = 'valueInAnotherBlock';
```

**Comment by jlongster** [comment]
Not going to do this, sorry. It would require a lot more complexity, and I think this style fails in some cases where you have a really long variable name and it doesn't make sense to push everything over. This is an arbitrary style and we're going to stick with a consistent `var variable = value`.

It technically would be very hard, just to expand. What do you do when a comment separates a group of variables? We interleave the comments after printing the nodes, so we have no knowledge of where comments are places while printing variables.

**Comment by Matt-Hill-Harness** [comment]
I think it would be relatively easy to allow users to plug in an existing alignment tool.  All IDEs support them.

**Comment by LinBoLen** [comment]
pls rethink about it @jlongster

**Comment by TaberIV** [comment]
I do understand this would be a complicated thing to implement, but why not add an option for prettier to leave existing spacing like this alone? It is subjective, and does fail in some places, but not always.

**Comment by lydell** [comment]
https://prettier.io/docs/en/option-philosophy.html
