### ISSUE TITLE
Handle yoda condition

### ISSUE THREAD

**Issue by evanliomain** [jlongster/prettier#189]
Add an option (or in default behavior) to handle yoda condition.

# BAD
```javascript
const myVar = test >= 0 ? 1 : 0;

if (myVar === 1) {
  return test / 2 * 100 + 4;
}
```

# GOOD
```javascript
const myVar = 0 <= test ? 1 : 0;

if (1 === myVar) {
  return 4 + 100 * test / 2;
}
```

Note that all constants (ie: magic number, `null`, `undefined` and string) are print as first as possible in all expressions.

Except for `<` and `<=` which should be used instead of `>` and `>=`.

**Comment by demoneaux** [comment]
This doesn't seem like something suitable for Prettier. Prettier is just a JavaScript formatter, which should not modify the code and the AST. Something like this is better suited to a JavaScript codemod or a Babel plugin which can transform comparison order.

**Comment by hnordt** [comment]
Usually I like to keep the constant at the right side and the thing that is being tested at the left side, that's the reason I don't like yoda.

**Comment by evanliomain** [comment]
@hnordt : Yes absolutely. Their are pros and cons for the yoda condition rule. You should be able to configure it to either have them always or never.
The point is to not have code with yoda condition somewhere, and no yoda condition elsewhere.

@demoneaux : It not modify AST since one of part is a constant, and so you can't introduce a bug with switch members. This feature is like the [eslint yoda rule](http://eslint.org/docs/rules/yoda).

**Comment by jlongster** [comment]
This is a highly subjective rule, easily apparent in the above 2 comments :D 

We don't intend to be eslint and will not introduce any configuration, so the formatting we provide must work for everyone. This means we generally will not restructure your code. You code how you want to. We just make sure it's formatted consistently. (as @demoneaux said).

It's pretty easy to combine this with eslint so you can take advantage of eslint's rich ecosystem of rules. See #165 also. Also see https://github.com/kentcdodds/prettier-eslint.
