### ISSUE TITLE
Long imports and exports don't respect max line-length

### ISSUE THREAD

**Issue by tylergaw** [jlongster/prettier#19]
I'm not sure if this is intended or a problem, but here's an example:

![](https://cl.ly/3i353s1P3w2F/Screen%20Recording%202017-01-10%20at%2011.31%20AM.gif)

Any `import {...} from 'package'; lines that exceed the max line length are not wrapped.

Was expecting something like: (or similar)
```js
import {
  fish, 
  horse, 
  dog, 
  animal, 
  dog, 
  bird, 
  ford as dorf, 
  river, 
  etc
} from '../package.js'
```

**Comment by conorcussell** [comment]
Same issue with `export = { name1 }` style syntax. 

<img width="720" alt="screen shot 2017-01-10 at 16 39 06" src="https://cloud.githubusercontent.com/assets/4960622/21815100/64e3f590-d753-11e6-9681-d71a59a1ae61.png">

**Comment by demoneaux** [comment]
I've been working on some changes locally which might help fix that. Will send a PR soon.

**Comment by OClyde** [comment]
There's still an issue when one import exceeds the max line length.

As an example...

```
import { ExtremlyLongComponentNameWithoutSpaces } from 'extremly/long/path/to/component.ts';
```
...could be handled by...
```
import {
  ExtremlyLongComponentNameWithoutSpaces
} from 'extremly/long/path/to/component.ts';
```

Not too crucial though, but still it could be solved. Worked around by adding a comment, which is doing the trick and prevents the one-line formatting, if someone runs into the same issue:
```
import {
  ExtremlyLongComponentNameWithoutSpaces
  // won't be reset by prettier!
} from 'extremly/long/path/to/component.ts';
```

**Comment by duailibe** [comment]
@OClyde This is intended behavior. We intentionally don't split if there's only one specifier in the import

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#imports
