### ISSUE TITLE
Avast issue with prettier v0.0.6 install

### ISSUE THREAD

**Issue by stoe** [jlongster/prettier#193]
Can't install or build v0.0.6 due to the below warning.

![](https://cl.ly/1T1o2o0F112V/Screen%20Recording%202017-01-14%20at%2015.37.gif)

![image](https://cloud.githubusercontent.com/assets/203805/21955630/70d6d9de-da6f-11e6-9988-4d138fa72f00.png)

Using `yarn add prettier@0.0.5` installs without the infection message, but using `yarn add prettier` raises the above infection warning from Avast.

![image](https://cloud.githubusercontent.com/assets/203805/21954041/256b0f88-da47-11e6-9ee2-c17858cd40f4.png)

---

I've also reported this earlier in https://github.com/jlongster/prettier-atom/issues/19

**Comment by stoe** [comment]
It looks like Avast is detecting `docs/prettier.min.js` as a trojan.
This happens for v0.0.6 and v0.0.7, but not for v0.0.5

I haven't yet found why exactly that threat is detected in code.

**Comment by stoe** [comment]
Seems to be fixed in v0.0.10

**Comment by demoneaux** [comment]
Probably something to do with Avast’s detection, seems like a false positive as there shouldn't be any trojans or viruses in the minified build of Prettier.
