### ISSUE TITLE
JSX comments have extra newline

### ISSUE THREAD

**Issue by joarwilk** [jlongster/prettier#20]
Comments in this style
```
{/* Some comment */}
<div />
```

are replaced with 
```
{}
<div />
```
I'm assuming its a bug?

**Comment by vjeux** [comment]
Repro case

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%2F*%20Some%20comment%20*%2F%7D%5Cn%20%20%3Cdiv%20%2F%3E%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
#482 fixes this, although the output is not desirable:

```js
{/* Some comment */
}
<div />;
```

I will leave this issue open to track that.

**Comment by vjeux** [comment]
I'm on master and it doesn't seem to display what you mentioned.

```js
echo '<div>{/* comment */}</div>' | ./bin/prettier.js
<div>{}</div>;
```

**Comment by vjeux** [comment]
There is a missing case where both preceding and following nodes are undefined. It doesn't attach the comments

https://github.com/jlongster/prettier/blob/master/src/comments.js#L203

**Comment by jkarttunen** [comment]
Not only comments, but also includes.
I'm doing marketing script automation, and bundling stuff without js modules with gulp-include (to keep end result readable).
If i run prettier on source files like this:

```
try{
  //=include ./decision_engine.js   
}catch (error) {
    
}
```
it completely breaks my build flow.

**Comment by duailibe** [comment]
@jkarttunen what do you mean by break your build flow? And why does that happen? Current output of the code you posted:

```js
try {
  //=include ./decision_engine.js
} catch (error) {}
```
Which seems reasonable to me. Can you tell us what your use case is? Also I think you can open a new issue for this. Thanks!
