### ISSUE TITLE
[JSX] When a line starts with a closing element, break ensuing elements onto newlines.

### ISSUE THREAD

**Issue by rattrayalex** [jlongster/prettier#202]
if `prettier` splits this...
```jsx
<div>
  <div>{pretend} {"there's"} {a lot of children here}</div><span>foo</span>
</div>
```
into this...
```jsx
<div>
  <div>
    {pretend} 
    {"there's"} 
    {a lot of children here}
  </div><span>foo</span>
</div>
```
...we should add a line after the `</div>`, moving `<span>foo</span>` to its own line. 

I may have this partially solved, especially thanks to a recent helpful tip from @jlongster

**Comment by vjeux** [comment]
On master,

```js
<div>
  <div>{pretend} {"there's"} {a lot of children here}</div><span>foo</span>
</div>
```

stays as is, is it intended?

**Comment by rattrayalex** [comment]
Depends how long the pretend children are...

1. if pretend-children.length > 80 - indent
```
<div>
  <div>
    {pretend} 
    {"there's"} 
    {a lot of children here}
  </div>
  <span>foo</span>
</div>
```
2. if opening-and-closing-div.length + pretend-children.length > 80 - indent
```
<div>
  <div>
    {pretend} {"there's"} {a lot of children here}
  </div>
  <span>foo</span>
</div>
```
3. if opening-and-closing-div.length + pretend-children.length + span-with-children.length > 80 - indent
```
<div>
  <div>{pretend} {"there's"} {a lot of children here}</div>
  <span>foo</span>
</div>
```
4. if opening-and-closing-div.length + pretend-children.length + span-with-children.length < 80 - indent
```
<div>
  <div>{pretend} {"there's"} {a lot of children here}</div><span>foo</span>
</div>
```
In this case, if you don't do any pretending, (4) is chosen, because that whole line is shorter than 80.

Does that make sense?

**Comment by vjeux** [comment]
Okay, nevermind... I wrote `--printWidth` instead of `--print-width`. It's working awesomely :)

**Comment by vjeux** [comment]
cc @jlongster, some incarnation of #301 would be useful.
