### ISSUE TITLE
Invalid formatting for multiline template strings and trailing comma option enabled

### ISSUE THREAD

**Issue by n1k0** [jlongster/prettier#208]
prettier 0.0.7, trailing comma option enabled. Source:

```js
const x = fn(`
hey
`)
```

[Transformed](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20x%20%3D%20fn(%60%5Cnhey%5Cn%60)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Afalse%7D%7D):

```js
const x = fn(
  `
hey
`,
);
```

The added trailing comma makes the code invalid.

**Comment by vjeux** [comment]
See this discussion: https://github.com/jlongster/prettier/issues/68

The trailing commas option also adds them for function call arguments (https://github.com/tc39/proposal-trailing-function-commas), which is now at stage 4 at tc39 which means that this is accepted and completed and waiting for engines to implement it.

You can use this babel transform to make it work: https://babeljs.io/docs/plugins/syntax-trailing-function-commas/

**Comment by n1k0** [comment]
Oh, I see. It's a little that generated code enforces usage of a transpiler though. I feel like at least one real world browser impl. of a leveraged feature should be a hard prerequisite :)

Anyway, keep up the great job folks :+1:
