### ISSUE TITLE
Don't remove semicolon from exports

### ISSUE THREAD

**Issue by knowbody** [jlongster/prettier#22]
#### expected behavior:

```js
export default MyComponent;
```

#### current behavior:

```js
export default MyComponent
```

**Comment by bakkot** [comment]
When fixing, be sure not to add parentheses when exporting class or function declarations:

```js
export default function(){}
```

should not get a semicolon after it.

**Comment by demoneaux** [comment]
I've been working on some changes locally which might help fix that. Will send a PR soon.

**Comment by oviava** [comment]
@demoneaux also, not sure if related - usually the `export` is the last line so the same rule might also be removing new lines at EOF

**Comment by demoneaux** [comment]
I've opened #101 to fix this. I'm not too sure if the `export` is what causes EOF to be missing though.

**Comment by leahaense** [comment]
It adds a semicolon when the default export is an interface, imho this shouldn't happen
