### ISSUE TITLE
[JSX] if else case in JSX

### ISSUE THREAD

**Issue by jarvisaoieong** [jlongster/prettier#226]
```jsx
const View = ({number}) => {
  return (
    <div>
    	{number > 1 &&
          <div>amazing</div>
        || number > 2 &&
           <div>awesome</div>
        ||
           <div>prettier</div>
        }
    </div>
  )
}
```

repo case: https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20View%20%3D%20(%7Bnumber%7D)%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%5Ct%7Bnumber%20%3E%201%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%3Cdiv%3Eamazing%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%7C%7C%20number%20%3E%202%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3Eawesome%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%7C%7C%5Cn%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3Eprettier%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by vjeux** [comment]
Related to #89

**Comment by vjeux** [comment]
This now outputs

```js
const View = ({ number }) => {
  return (
    <div>
      {
        number > 1 && <div>amazing</div> ||
          number > 2 && <div>awesome</div> ||
          <div>prettier</div>
      }
    </div>
  );
};
```

which is what is intended. We may want to tweak the result but the bug is no longer there so closing :)
