### ISSUE TITLE
Turns ["catch"] into ."catch"

### ISSUE THREAD

**Issue by amytych** [jlongster/prettier#23]
The bracket notation used here to avoid issues in older browsers that don't handle reserved words well is being changed to incorrect syntax

`["catch"]` becomes `."catch"` causing `Uncaught SyntaxError: Unexpected string`

**Comment by jlongster** [comment]
Interesting, we're missing the brackets. Should be a small fix, thanks.

**Comment by amytych** [comment]
Nah, thank you! This is great!
