### ISSUE TITLE
await strips parentheses

### ISSUE THREAD

**Issue by marudor** [jlongster/prettier#239]
```
class foo {
  async bar() {
    return (await this.foo()).size;
  }
  foo() {}
}
```

->

```
class foo {
  async bar() {
    return await this.foo().size;
  }
  foo() {}
}
```
as you can see this changes how the function behaves.

**Comment by hzoo** [comment]
This is fixed in https://github.com/jlongster/prettier/pull/185 (was the first pr/commit after 0.0.7) so just needs a new release
