### ISSUE TITLE
Spaces inside import brackets are removed

### ISSUE THREAD

**Issue by joarwilk** [jlongster/prettier#24]
`import React, { Component } from 'react';`

Gets replaced with 

`import React, {Component} from "react";`

I havent seen that convention before. For reference,

`const thing = {React};`

Transforms into

`const thing = { React };`

**Comment by jlongster** [comment]
Thanks, this is an easy fix. Will do it soon.

**Comment by wmertens** [comment]
Note that the `{Component}` form is the default configuration of XO (https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js#L199). I kinda like it…
