### ISSUE TITLE
[MemberExpression] Missing parenthesis for object expressions and method calls

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#243]
```js
({}.a().b());
({}).a().b();
```

outputs

```js
{}.a().b();
{}.a().b();
```

which is invalid

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22(%7B%7D.a().b())%3B%5Cn(%7B%7D).a().b()%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by yamafaktory** [comment]
@vjeux I will create a PR for the second case in few minutes!

**Comment by vjeux** [comment]
I'm curious, why only the second? As far as I can see both have the same AST. Is there something I'm missing?

**Comment by jlongster** [comment]
Hm, how is `{}.a().b();` invalid? Aren't the two expressions the same and can be reduced the that form?

**Comment by vjeux** [comment]
```
{a: 1}
```

Is ambiguous in JavaScript. It can either be a block with a label a for the value 1 or an object with a key a and value 1.

For `{a: 1}.a()` js will parse it as a block and be invalid. To make it parse as an object you need parenthesis, either around the object or the whole expression

**Comment by jlongster** [comment]
Ah, I thought the member lookup would disambiguate it. I've dealt with that behavior behavior before but thought it was clear here. Gotcha, makes sense!
