### ISSUE TITLE
Missing parenthesis for functions left of a template literal

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#244]
```js
(function() {})()``;
(function() {})``;
```

outputs

```js
function() {}()``;
function() {}``;
```

which is invalid

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22(function()%20%7B%7D)()%60%60%3B%5Cn(function()%20%7B%7D)%60%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

Those test262 are testing crazy things :p

**Comment by vjeux** [comment]
@existentialism your commit fixed the first case

```js
(function() {})()``
```

but the second

```js
(function() {})``
```

still doesn't work fyi

**Comment by existentialism** [comment]
Derp, will fix!

**Comment by vjeux** [comment]
There's like 50 test cases of this form on the test262 suite, so it's pretty spammy, even though it's never going to happen in practice :p
