### ISSUE TITLE
Reserved keywords as variable names with escaping

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#245]
```js
var \u{63}ase = 123;
```

outputs

```js
var case = 123;
```

which is invalid.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22var%20%5C%5Cu%7B63%7Dase%20%3D%20123%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

I had no idea you could even write that! This happens for all the reserved words (`switch`, `let`, `var`...). The proper fix is likely to escape the first character for all of them.

**Comment by lydell** [comment]
I tried that in the Node REPL:

```
> var \u{63}ase = 123;
var \u{63}ase = 123;
    ^^^^^^^^^
SyntaxError: Keyword must not contain escaped characters
```

¯\\_(ツ)_/¯

**Comment by jlongster** [comment]
@lydell I think that's the correct behavior and the problem here is that we allow it, I think? (allow = happily convert) Not exactly sure what we should do.

**Comment by hzoo** [comment]
Yeah just means https://github.com/babel/babylon/issues/206 would need to be fixed

**Comment by vjeux** [comment]
Actually, nevermind. The keywords are not valid JavaScript and the rest should not be escaped, we should just print them as is. Closing this.
