### ISSUE TITLE
SyntaxError: Identifier directly after number

### ISSUE THREAD

**Issue by brunolemos** [jlongster/prettier#256]
Before/after prettier:

```diff
-const str4 = () => ((1 + Math.random()) * 0x10000 | 0).toString(16).substring(1);
+const str4 = () => (1 + Math.random()) * 65536 | 0.toString(16).substring(1);
```

Notice how the parentheses got removed, leaving a `0.toString`.

This new line is not valid.
It throws an javascript error on execution or even when trying to run prettier again.

(and also I think `0x10000` should be preserved 🙃)

**Comment by vjeux** [comment]
Thanks! The issue is already tracked by https://github.com/jlongster/prettier/issues/96#issuecomment-271850172

For 0x10000, that would be nice indeed to preserve it. Need to figure out how hard it would be to.

**Comment by brunolemos** [comment]
@vjeux thanks

**Comment by vjeux** [comment]
Could you open an issue to track the fact that 0x10000 is not kept as is? We need to fix it :) Thanks

**Comment by vjeux** [comment]
#257 solves the 0x10000 issue, it turns out it was an easy fix :)

**Comment by brunolemos** [comment]
Oh, great!
