### ISSUE TITLE
Missing parenthesis around arrow function argument for reserved keywords

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#260]
Okay, this one is really crazy.

```js
var a = (await) => 1;
```

outputs

```js
var a = await => 1;
```

and doesn't parse anymore. Need to put parenthesis around.

Note that it only works in non-strict mode. Strict mode fortunately makes having such crazy variable names invalid.

Because we put the strict option by default in the babylon parser, it can only be tested on the flow parser.

**Comment by jlongster** [comment]
Fun!

**Comment by vjeux** [comment]
Okay, actually I'm not sure what's going on,

![image](https://cloud.githubusercontent.com/assets/197597/22007510/09361532-dc28-11e6-8d74-5d5fa2e9cb79.png)

this seems to be working without the parenthesis.

FYI, those are the keywords you can use as arguments:

```js
let
eval
await
yield
public
static
package
private
arguments
interface
protected
implements
```

```js
['do', 'if', 'in', 'for', 'let', 'new', 'try', 'var', 'case', 'else', 'enum', 'eval', 'null', 'this', 'true', 'void', 'with', 'await', 'break', 'catch', 'class', 'const', 'false', 'super', 'throw', 'while', 'yield', 'delete', 'export', 'import', 'public', 'return', 'static', 'switch', 'typeof', 'default', 'extends', 'finally', 'package', 'private', 'continue', 'debugger', 'function', 'arguments', 'interface', 'protected', 'implements', 'instanceof']
  .forEach(keyword => { try { eval('var a = (' + keyword + ') => 1'); console.log(keyword); } catch(e) { } } )
```
