### ISSUE TITLE
Make `trailingComma` option more granular

### ISSUE THREAD

**Issue by sapegin** [jlongster/prettier#266]
This code:

```js
a(b.map(function(c) { return c; }));
```

is formatted like this:

```js
a(
  b.map(function(c) {
    return c;
  }),
);
```

with extra comma in a function call.

Demo: https://jlongster.github.io/prettier/#%7B%22content%22%3A%22a(b.map(function(c)%20%7B%20return%20c%3B%20%7D))%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by demoneaux** [comment]
This is due to `trailingCommas` enabling them by default in all places, including function parameters. This will probably be modified to allow disabling them for function parameters which is not an official ES syntax for now.

**Comment by jlongster** [comment]
Yeah, we need to make that option tiered. I'll rename this issue and if there are any other issues filed about this please dupe to this one.

**Comment by demoneaux** [comment]
What's the current perspective on the API? Recast allows a simple `true`/`false` config, as well as an object based config for specific features:

```
trailingComma: {
  objects: true,
  arrays: true,
  parameters: false
}
```

Should we do something similar, or make it simpler to reduce the config, and just allow all trailing commas, trailing commas except in function parameters, and no trailing commas?

**Comment by joefiorini** [comment]
Seems like supporting the recast options would make this tool the most flexible, but does that go against the goals of being an "opinionated JavaScript formatter"?

**Comment by tabazevedo** [comment]
I'd lean towards the `--trailing-commas` option just not adding them to function calls. The benefit of trailing commas is mostly apparent when adding elements to a list or reordering them and having better git diffs.

Its quite rare that you have a lot of instances in a codebase where there are enough arguments in a function call to warrant that they be on multiple lines _and_ that you'll change those arguments often enough to reap the benefits of trailing commas (vs. the pain of having to manually edit/ignore files from the formatting).

**Comment by joefiorini** [comment]
Ran into a good reason not to add trailing commas to function params: the node LTS doesn't support it! It's all well and good that babel transpiles my web code es2017, but I've purposefully stuck with es2015 in my node code so I don't have to introduce that complexity.

**Comment by sentience** [comment]
This is a blocker for our adoption of Prettier. We have a large codebase with trailing commas on arrays and objects that we don’t want to lose, but we can’t introduce non-standard trailing commas on function calls because files like our Webpack config are not transpiled by Babel.

**Comment by rhengles** [comment]
@sentience I just added this option in https://github.com/arijs/prettier-with-tabs/pull/1

**Comment by sbrandwoo** [comment]
I feel like the issue here is not the lack of configuration, but that trailing commas are not valid in function parameters?

Here's an other example, when the line is long enough to wrap the trailing comma is inserted:

```
const orderedUsers = users.sortBy(
    user => aLongFunctionNameThatCausesWrapping(user),
);
```

**Comment by erbridge** [comment]
Trailing commas are valid in function calls in ES7, but assuming that everyone who wants trailing commas can support ES7 syntax is flawed, IMO.

**Comment by jlongster** [comment]
This will be added in https://github.com/jlongster/prettier/pull/641. I think it's better to have a simple string option that indicates whether you want them in "currently valid" places or "all" places.

In that PR, by default, trailing commas will only be added in places that are known to be supported in all JS environments. The "all" option will add them everywhere we can though, like function args.

**Comment by oscar-b** [comment]
Maybe an option to set the desired ES target?

**Comment by tabazevedo** [comment]
@jlongster I think a generic `--trailing-commas` flag coupled with
