### ISSUE TITLE
Not splitting lines with object as function argument

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#268]
```js
it('should group messages with same created time', () => {
  expect(
    groupMessages(messages).toJS(),
  ).toEqual({
    '11/01/2017 13:36': [
      {message: 'test', messageType: 'SMS', status: 'Unknown', created: '11/01/2017 13:36'},
      {message: 'test', messageType: 'Email', status: 'Unknown', created: '11/01/2017 13:36'},
    ],
    '09/01/2017 17:25': [
      {message: 'te', messageType: 'SMS', status: 'Unknown', created: '09/01/2017 17:25'},
      {message: 'te', messageType: 'Email', status: 'Unknown', created: '09/01/2017 17:25'},
    ],
    '11/01/2017 13:33': [
      {message: 'test', messageType: 'SMS', status: 'Unknown', created: '11/01/2017 13:33'},
      {message: 'test', messageType: 'Email', status: 'Unknown', created: '11/01/2017 13:33'},
    ],
    '11/01/2017 13:37': [
      {message: 'test', messageType: 'SMS', status: 'Unknown', created: '11/01/2017 13:37'},
      {message: 'test', messageType: 'Email', status: 'Unknown', created: '11/01/2017 13:37'},
    ],
  });
});
```

This gets formatted like so 
```js
it("should group messages with same created time", () => {
  expect(
    groupMessages(messages).toJS()
  ).toEqual({ "11/01/2017 13:36": [ { message: "test", messageType: "SMS", status: "Unknown", created: "11/01/2017 13:36" }, { message: "test", messageType: "Email", status: "Unknown", created: "11/01/2017 13:36" } ], "09/01/2017 17:25": [ { message: "te", messageType: "SMS", status: "Unknown", created: "09/01/2017 17:25" }, { message: "te", messageType: "Email", status: "Unknown", created: "09/01/2017 17:25" } ], "11/01/2017 13:33": [ { message: "test", messageType: "SMS", status: "Unknown", created: "11/01/2017 13:33" }, { message: "test", messageType: "Email", status: "Unknown", created: "11/01/2017 13:33" } ], "11/01/2017 13:37": [ { message: "test", messageType: "SMS", status: "Unknown", created: "11/01/2017 13:37" }, { message: "test", messageType: "Email", status: "Unknown", created: "11/01/2017 13:37" } ] });
});
```

The `toEqual` function there is really strange. 

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22it('should%20group%20messages%20with%20same%20created%20time'%2C%20()%20%3D%3E%20%7B%5Cn%20%20expect(%5Cn%20%20%20%20groupMessages(messages).toJS()%2C%5Cn%20%20).toEqual(%7B%5Cn%20%20%20%20'11%2F01%2F2017%2013%3A36'%3A%20%5B%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'SMS'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A36'%7D%2C%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'Email'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A36'%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20'09%2F01%2F2017%2017%3A25'%3A%20%5B%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'te'%2C%20messageType%3A%20'SMS'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'09%2F01%2F2017%2017%3A25'%7D%2C%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'te'%2C%20messageType%3A%20'Email'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'09%2F01%2F2017%2017%3A25'%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20'11%2F01%2F2017%2013%3A33'%3A%20%5B%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'SMS'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A33'%7D%2C%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'Email'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A33'%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20'11%2F01%2F2017%2013%3A37'%3A%20%5B%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'SMS'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A37'%7D%2C%5Cn%20%20%20%20%20%20%7Bmessage%3A%20'test'%2C%20messageType%3A%20'Email'%2C%20status%3A%20'Unknown'%2C%20created%3A%20'11%2F01%2F2017%2013%3A37'%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D)%3B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by vjeux** [comment]
Thanks, this is a bug, right now the last function call doesn't get properly expanded.

**Comment by gaearon** [comment]
Is this the same case?

```js
export default store => {
  return callApi(endpoint, schema).then(
    response => next(actionWith({
      response,
      type: successType
    })),
    error => next(actionWith({
      type: failureType,
      error: error.message || 'Something bad happened'
    }))
  )
}
```

becomes

```js
export default store => {
  return callApi(
    endpoint,
    schema
  ).then(response => next(actionWith({ response, type: successType })), error => next(actionWith({ type: failureType, error: error.message || "Something bad happened" })));
};
```

**Comment by vjeux** [comment]
Yes, this is the same bug. One the last few launch blocking bugs

**Comment by vjeux** [comment]
Sorry it took so long to fix, turns out I was looking in the wrong place! https://github.com/jlongster/prettier/pull/462 fixes it
