### ISSUE TITLE
jshint comments breaking into new line

### ISSUE THREAD

**Issue by flpwgr** [jlongster/prettier#271]
First, really awesome tool!

Second, is there any way to prevent //jshint comments from breaking ?

ex:

```
function test(arg1,arg2,arg3) { //jshint ignore:line
  code here..
}
```

become:
```
function test(arg1,arg2,arg3) {
  //jshint ignore:line
  code here...
}
````

**Comment by jlongster** [comment]
Comments are currently somewhat buggy and I'm working on a rehaul of them now.

**Comment by jlongster** [comment]
See #275
