### ISSUE TITLE
Strange JSX indent

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#272]
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20foo()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%20className%3D%7Bstyles.filterAndActionButtons%7D%3E%5Cn%20%20%20%20%20%20%7B!this.props.isContactFormOpen%20%3F%20(%5Cn%20%20%20%20%20%20%20%20%3Cbutton%20className%3D%7Bstyles.headerButton%7D%20onClick%3D%7B()%20%3D%3E%20this.openContactForm()%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20Contact%5Cn%20%20%20%20%20%20%20%20%3C%2Fbutton%3E%5Cn%20%20%20%20%20%20)%20%3A%20(%5Cn%20%20%20%20%20%20%20%20%3Cbutton%5Cn%20%20%20%20%20%20%20%20%20%20className%3D%7Bstyles.headerButton%7D%5Cn%20%20%20%20%20%20%20%20%20%20disabled%3D%7Bthis.props.checkedPassengers.size%20%3D%3D%3D%200%7D%5Cn%20%20%20%20%20%20%20%20%20%20onClick%3D%7B()%20%3D%3E%20this.closeContactForm()%7D%5Cn%20%20%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%20%20Close%20contact%20form%5Cn%20%20%20%20%20%20%20%20%3C%2Fbutton%3E%5Cn%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%3Cbutton%5Cn%20%20%20%20%20%20%20%20className%3D%7Bstyles.headerButton%7D%5Cn%20%20%20%20%20%20%20%20disabled%3D%7Bthis.props.checkedPassengers.size%20%3D%3D%3D%200%7D%5Cn%20%20%20%20%20%20%20%20onClick%3D%7B()%20%3D%3E%20this.onExportContacts()%7D%5Cn%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20Export%5Cn%20%20%20%20%20%20%3C%2Fbutton%3E%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

The button inside the ternary there is pretty strange. Don't know what the preferred output here would be, but I feel like this gets pretty strange, especially in a bigger context (like it is in my actual code) where this gets some extreme indent compared to it's neighbours.

**Comment by vjeux** [comment]
Thanks, this is indeed a bug, there shouldn't be four spaces of indentation, just two.

**Comment by vjeux** [comment]
This is now fixed on 0.0.9
