### ISSUE TITLE
emacs: add support for js2-mode

### ISSUE THREAD

**Issue by sxn** [jlongster/prettier#273]
So currently https://github.com/jlongster/prettier/blob/master/editors/emacs/prettier-js.el#L67 makes it so that `defun-before-save` only works in `js-mode`, leaving anyone who uses other modes for editing JS (like [js2-mode](https://github.com/mooz/js2-mode)) out in the cold (or, you know, define their own hook function 😄 ). It would be nice to support `js2-mode` to avoid all of that. The change would be trivial:
```
(defun prettier-before-save ()
  "Add this to .emacs to run refmt on the current buffer when saving:
 (add-hook 'before-save-hook 'prettier-before-save)."
  (interactive)
  (when (member major-mode '(js-mode js2-mode)) (prettier)))
```

The list of supported modes/the mode which should be used could even be extracted into a customizable variable.

**Comment by demoneaux** [comment]
This can probably be closed since #276 has been merged.
