### ISSUE TITLE
Why is `arg =>` put on a newline?

### ISSUE THREAD

**Issue by fingermark** [jlongster/prettier#274]
I'm looking at this prettier [formatted](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%20Observable%20%7D%20from%20'rxjs%2FObservable'%3B%5Cnimport%20%7B%20replace%20%7D%20from%20'react-router-redux'%3B%5Cnimport%20*%20as%20ActionTypes%20from%20'..%2FActionTypes'%3B%5Cnimport%20%7B%20receiveUsers%20%7D%20from%20'..%2Factions'%3B%5Cnimport%20%7B%20ajax%20%7D%20from%20'rxjs%2Fobservable%2Fdom%2Fajax'%3B%5Cn%5Cnexport%20default%20function%20searchUsers(action%24)%20%7B%5Cn%20%20return%20action%24.ofType(ActionTypes.SEARCHED_USERS)%5Cn%20%20%20%20.map(action%20%3D%3E%20action.payload.query)%5Cn%20%20%20%20.filter(q%20%3D%3E%20!!q)%5Cn%20%20%20%20.switchMap(q%20%3D%3E%5Cn%20%20%20%20%20%20Observable.timer(800)%20%2F%2F%20debounce%5Cn%20%20%20%20%20%20%20%20.takeUntil(action%24.ofType(ActionTypes.CLEARED_SEARCH_RESULTS))%5Cn%20%20%20%20%20%20%20%20.mergeMap(()%20%3D%3E%20Observable.merge(%5Cn%20%20%20%20%20%20%20%20%20%20Observable.of(replace(%60%3Fq%3D%24%7Bq%7D%60))%2C%5Cn%20%20%20%20%20%20%20%20%20%20ajax.getJSON(%60https%3A%2F%2Fapi.github.com%2Fsearch%2Fusers%3Fq%3D%24%7Bq%7D%60)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map(res%20%3D%3E%20res.items)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map(receiveUsers)%5Cn%20%20%20%20%20%20%20%20))%5Cn%20%20%20%20)%3B%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D) code and having `q =>` put on a newline is adding another level of indentation, which means we're now 2 spaces closer to the wrap.  I couldn't find a ticket for this, but (if we have the space for it within the printWidth) would it be possible to have

```
    .switchMap(q =>
        Observable
```

Instead of

``` 
    .switchMap(
      q =>
        Observable
```

**Comment by vjeux** [comment]
Thanks for the report! This is a bug, it should be as you mentioned.

**Comment by jlongster** [comment]
Originally I didn't expect people to write block-less arrow functions with the code on the next lines, which is why this crops up in some places. We probably need to tweak the algorithm for arrow functions to better support this case.

**Comment by vjeux** [comment]
Same issue here https://github.com/jlongster/prettier/pull/354/files/fcd34e384866f2b7e88a60c253724a7823c529b3#r97123465

This may be related to the work we are doing with MemberExpression
