### ISSUE TITLE
"use strict" indentation for anonymous function passed as argument

### ISSUE THREAD

**Issue by acdha** [jlongster/prettier#29]
I ran prettier on some old code which used the classic `jQuery(function() …)` structure and was a little surprised by the results. Here's a reduction:

```js
jQuery(function() {
    'use strict';
    return 1;
});
``` 

placed the `use strict` declaration on the same line as the function (and added a trailing space after the semicolon):

```js
jQuery(function() { "use strict";  
  return 1;
});
```

With similar constructs, this doesn't happen:

```
$ prettier <(echo -e "function foo () {\n\t'use strict';\n\treturn 1;\n}")
function foo() {
  "use strict";

  return 1;
}
$ prettier <(echo -e "var foo = function() {\n\t'use strict';\n\treturn 1;\n};")
var foo = function() {
  "use strict";

  return 1;
};
$ prettier <(echo -e "(function() {\n\t'use strict';\n\treturn 1;\n})();")
(function() {
  "use strict";

  return 1;
})();
```

I haven't looked to see what's triggering this but it's probably connected to the line-length logic since it'll wrap once you hit that threshold:

```
$ prettier <(echo -e "otherFunctionWithANameSoLongThatItWillExceedTheMaximumLineLength(function() {\n\t'use strict';\n\treturn 1;\n});")
otherFunctionWithANameSoLongThatItWillExceedTheMaximumLineLength(function() {
  "use strict";

  return 1;
});
```

**Comment by jlongster** [comment]
What's weird is that newlines after the opening curly in a function expression is one of the simplest rules. It should always output a newline after `{`. I'll look into this.
