### ISSUE TITLE
Semi-colons stripped from multi-line default exports

### ISSUE THREAD

**Issue by joefiorini** [jlongster/prettier#292]
I am running prettier against master for all the great jsx fixes. I'm still seeing it strip semi-colons from some default exports.

My original code:

```jsx
export default ({ children }) => (
  <Provider store={store} key="provider">
    <IntlProvider locale="en">
      {children}
    </IntlProvider>
  </Provider>
);
```

Prettier-formatted code:

```jsx
export default ({ children }) => (
  <Provider store={store} key="provider">
    <IntlProvider locale="en">
      {children}
    </IntlProvider>
  </Provider>
)
```

I know there have been other issues around semi-colons in default exports but it seems this is an edge case that hasn't been fixed yet.

**Comment by vjeux** [comment]
Thanks for reporting this! It indeed hasn't yet been fixed.

@existentialism do you want to take a shot at this one since you did #287?

**Comment by existentialism** [comment]
Gah, not sure why I didn't think about this. Fix otw!

**Comment by vjeux** [comment]
@existentialism btw, we are on gitter if you want to chat with us :) https://gitter.im/jlongster/prettier

**Comment by joefiorini** [comment]
@existentialism @vjeux thanks for the quick feedback! you all rock!

**Comment by joefiorini** [comment]
Thanks @existentialism! When I saved the file with the above example in it, I can confirm that it put the semi-colon back!
