### ISSUE TITLE
Non-Optional Spaces Removed From JSX

### ISSUE THREAD

**Issue by PabloSichert** [jlongster/prettier#30]
For

```jsx
<span>
    foo <span>bar</span>
</span>
```

I got

```jsx
<span>
  foo<span>bar</span>
</span>;
```

which would render `foo bar` vs `foobar`.

---

Thanks for the great tool, though! Hope to adopt it once it becomes stable :sun_with_face:

**Comment by jlongster** [comment]
Good catch, thanks. We try to format JSX when we can help, which is why the indentation before `foo` is changed, but we certainly shouldn't remove this space.

**Comment by vramana** [comment]
Closing this in favour of #73
