### ISSUE TITLE
Comments stripped from empty functions

### ISSUE THREAD

**Issue by acdha** [jlongster/prettier#31]
This is definitely an edge case but it might surprise people with placeholders, etc. if they aren't carefully reviewing changes:

```js
function foo() {
	//foobar
}
```

becomes:

```js
function foo() {}
```

Adding any sort of real work to that code will cause the comment to be retained:

```js
function foo() {
	//foobar
        1;
}
```

```js
function foo() {
  //foobar
  1;
}
```

**Comment by jlongster** [comment]
Good call, I think that's called a "dangling" comment and we might just not be outputting those.

**Comment by deoxxa** [comment]
I do this every now and then in empty `catch` handlers, like this:

```js
doTheThing().then(something).then(somethingElse).then((res) => {
  console.log(res);
}).catch((err) => {
  /* do nothing - no way to recover from this error */
})
```

It makes no operational difference to the program, but it serves as documentation that the error has been considered and ignored on purpose.

**Comment by n1k0** [comment]
This comes especially annoying when iterating over some implementation and using the format-on-save feature of some editor's plugin - which turns being totally unusable in these circumstances :)

**Comment by jlongster** [comment]
Moved to #275
