### ISSUE TITLE
JSX spaces

### ISSUE THREAD

**Issue by daltones** [jlongster/prettier#32]
In Prettier's live demo there's this:
```jsx
<div>
  hello ${name}! JSX is <strong>supported</strong>
</div>
```

And it's formatted as:
```jsx
<div>
  hello ${name}! JSX is<strong>supported</strong>
</div>
```

We can see that spaces around tags [and regular JS expressions] in the same line are missing.

You can also reproduce the issue this way:
```jsx
<div>
  text {name} more text and <em>tag</em> and text
</div>
```

Formatted as:
```jsx
<div>
  text{name}more text and<em>tag</em>and text
</div>
```

**Comment by jlongster** [comment]
Dupe of https://github.com/jlongster/prettier/issues/30, thanks!

**Comment by daltones** [comment]
Wow, that was fast lol

Thanks for the new tool! 😃
