### ISSUE TITLE
[JSX] Props ordering

### ISSUE THREAD

**Issue by codejunkienick** [jlongster/prettier#323]
Is there a chance to have an option for sorting props on JSX elements? Would be great to sort them in alphabetical order and have priority for having true values at the top

```
<Example
c
d
aFunc={() => console.log('')}
bProp={<Element />}
/>
```

**Comment by demoneaux** [comment]
This isn't really suitable for Prettier. Prettier is just a JS formatter, and should not modify the AST like that. This should probably be done by a JS codemod or a Babel plugin.

**Comment by lydell** [comment]
This would have execution order issues.

```js
<Example
  b={prepareLunch()}
  a={eatLunch()}
/>
```
→
```js
<Example
  a={eatLunch()}
  b={prepareLunch()}
/>
```

**Comment by vramana** [comment]
For the reason pointed out by @lydell, this is not possible. Hence closing this issue.
