### ISSUE TITLE
Empty function split across 2 lines;

### ISSUE THREAD

**Issue by karl** [jlongster/prettier#324]
When you have an empty function it is split across 2 lines. I would have expected it to be on a single line.

Before:

```js
const noop = () => {};

const noop = function() {};
```

After:

```js
const noop = () => {
};

const noop = function() {
};
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20noop%20%3D%20()%20%3D%3E%20%7B%7D%3B%5Cn%5Cnconst%20noop%20%3D%20function()%20%7B%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

Apologies if this has already been reported. I did a quick search of issues and couldn't find anything that matches it.

**Comment by vjeux** [comment]
I've also seen this and it's a bit weird indeed. Maybe we should figure out a list of things that should be split and things that shouldn't.

`if`, `for`, `while` likely should. `function` and `arrow function` may not be.

**Comment by jlongster** [comment]
@vjeux I thought you wanted blocks to be explicitly broken up on new lines? :)

Sure, we can special-case it based on the parent node type. Just need to do 

```js
const parent = path.getParentNode().getValue();
if(namedTypes.FunctionExpression.check(parent) ||
   namedTypes.ArrowFunctionExpression.check(parent)) {
  return "{}";
}
return concat(["{", hardline, "}"]);
```

**Comment by vjeux** [comment]
I was mainly annoying by `if then else` and `try catch` when I looked at it.

**Comment by jlongster** [comment]
Ah ok. We have a clear fix so changing this to bug.
