### ISSUE TITLE
Make chaining indentation configurable

### ISSUE THREAD

**Issue by wmertens** [jlongster/prettier#35]
I always thought that indenting chained functions was problematic, since as far as the parser is concerned, there is no block until it encounters the `.`.

That's why I prefer
```js
fn()
.then(foo => bar())
.finally(cleanup)
```

indenting would mean this code style:
```js
fn().
  then(foo => bar()).
  finally(cleanup)
```
...which is of course terrible because the `.` is easy to miss at the end of the line and you need to manage it when moving lines around.

Hence: please make chaining indentation configurable.

**Comment by jlongster** [comment]
I'm not sure what you mean. I haven't run into any problems with this style:

```js
fn()
  .then(foo => bar())
  .finally(x => x);
```

Which is close to your original example, which is what you are saying you want? JS parsers should have no problem with this.

**Comment by wmertens** [comment]
Myeah, I suppose that this is a very minor request, certainly if you want to keep the number of options small. Closing.
