### ISSUE TITLE
Feature request: vertical alignment.

### ISSUE THREAD

**Issue by SanderElias** [jlongster/prettier#350]
I would like to propose to add vertical alignment. 
And if that's not feasible, not messing up existing alignments.
I use vertical alignment for example like this:

```
                xx.name        = "sliderManager";
                xx.save        = save;
                xx.slides      = defaultList();
                xx.showConfirm = showConfirm;
```
And in objects like this:
```
{
                        id:          utilMakeHash(),
                        key:         i.key,
                        title:       i.title,
                        description: i.description,
                        img:         i.url
                    }
```
The reason for me doing this is twofold,
1. assignments really stands out
2. way better readabillity.

I know not all people think this is pretty, but that's not the point of it. It really improves the readability, and ease of understanding of code.

BTW, the spaces on front are copy/paste issues, and not part of the proposal!

**Comment by vramana** [comment]
This has been previously asked and has been closed because it's too subjective. I can't find the comment right now. @vjeux or @jlongster will address this.

**Comment by hzoo** [comment]
Looks like https://github.com/jlongster/prettier/issues/188 if you meant that

**Comment by vramana** [comment]
@hzoo Yes. Thanks.

**Comment by vjeux** [comment]
We should start a document with the styles of formatting we discussed and are not going to implement.

**Comment by hzoo** [comment]
maybe should start labeling those too for easy reference

**Comment by LinBoLen** [comment]
please support this feature
