### ISSUE TITLE
Prettier escapes quoted Unicode object values 

### ISSUE THREAD

**Issue by Dema** [jlongster/prettier#351]
It just started to escape quoted Unicode text in object property value.
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22var%20a%20%3D%20%7B%5Cn%20%20%27%D1%82%D0%B5%D1%81%D1%82%27%3A%20%27%D1%82%D0%B5%D1%81%D1%82%27%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D
This could be something related to commit 340da01

I'm using babylon parser.

**Comment by vjeux** [comment]
We had many issues with unicode characters so now we are aggressively escaping all of them.

We need to figure out what we should do there, I'm not sure this is the right call, but at least we now emit valid JavaScript.
