### ISSUE TITLE
[Comments] Trailing single-line comments are wrapped to the next line

### ISSUE THREAD

**Issue by acdha** [jlongster/prettier#36]
I had a bit of code where a trailing comment was moved to the next line when there's another statement after the function. This can cause confusion since it requires you to read the comment to know whether it applies to the line before or after and it looks like it would actually cause things like `// eslint-disable-line` to apply to a different statement.

```js
function foobar() {
	var foo = bar;
	var bar = fooBarBaaz(); // foo all the bars

	var baaz = 'quux';
}
```

becomes:

```js
function foobar() {
  var foo = bar;
  var bar = fooBarBaaz();
  // foo all the bars
  var baaz = "quux";
}
```

This does not happen if the comment is on the last line of a function.

**Comment by jlongster** [comment]
Comments are probably where most of the subtle bugs are right now. They're pretty difficult to get right, but this is definitely problematic. I think it'll take a few weeks to sort out these kinds of bugs, but we'll get there.

**Comment by jepler** [comment]
prettier sure doesn't know what to make of ASCII art that is laid out to the right of the real code, such as this example (input):
~~~~
//                                           60 chars -->   |
function makeComponent(): int {
  return {                   //                 (__)
    longCall() {             //                 (oo)
      complicatedFunction(   //           /------\/
        importantArgument(), //          / |    ||
        secondaryArgument()  //         *  /\---/\
      );                     //            ~~   ~~
      weirdStyle({ prop: 1 }, 1, 2, 3);
    },
    render() {
      const user = { name: "James" };
      return (
        <div>
          hello ${name}! JSX is<strong>supported</strong>
        </div>
      );
    }
  };
}
~~~~
but honestly I don't know what you do with devs who insist on that sort of thing; tell them to cut it out I suppose.

**Comment by acdha** [comment]
@jepler I've seen a few cases where someone had some sort of diagram / flowchart which was  important but I would think a reasonable position would simply be “Make it a full multi-line comment block”.

**Comment by jlongster** [comment]
inline comments in all positions are extremely difficult. The case where there inline comments beside function call arguments is a known issue in recast as well, and it actually reclassifies those comments as leading comments (moves them up before the expression). I think right now we copy that behavior sometimes too.

But yes, there are going to be times where there is only so much we can do, and users need to change how they write a specific style so that it formats better. We can make inline comments better to some degree, but I'm not sure how far we can go.

**Comment by karmatics** [comment]
This one is a rather big issue for me, I tend to use the space to the right for a comment whenever it helps, such as to say what that object property is or what have you

**Comment by jlongster** [comment]
See above PR
