### ISSUE TITLE
Export extension syntax not formatted correctly

### ISSUE THREAD

**Issue by randycoulman** [jlongster/prettier#360]
Code using the [export extensions transform](https://babeljs.io/docs/plugins/transform-export-extensions/) is not formatted correctly.

When running prettier on one of my projects, the following:

```js
export reducer from './reducer'
```

was formatted as:

```js
export { reducer } from './reducer';
```

Note the addition of the curly braces, which changes the semantics of the `export` statement.

**Comment by vjeux** [comment]
Repro case: 
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20reducer1%20from%20'.%2Freducer'%3B%5Cnexport%20%7B%20reducer2%20%7D%20from%20'.%2Freducer'%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by randycoulman** [comment]
Yes, I just used your repro link above to try the `export * as ns from 'mod';` as well, and it gets curly braces too.

**Comment by vjeux** [comment]
If you are looking to contribute, this should be a pretty simple fix. You can use astexplorer.net to figure out the AST structure and then in src/printer.js search the node type and see how it is being printed

**Comment by vjeux** [comment]
The issue you linked to is awesome! Thanks for writing it up.
