### ISSUE TITLE
Empty switch: extraneous blank line

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#368]
Input:

```js
switch(1){}
```

Output:

```js
switch (1) {

}
```

Expected:

```js
switch (1) {
}
```

(just like empty `if`)

Do we care? ¯\\\_(ツ)\_/¯

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22switch(1)%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by lydell** [comment]
This was found using my fuzzer in #371

**Comment by vjeux** [comment]
Yeah, we should fix that! Thanks
