### ISSUE TITLE
Error thrown on  ES2015 Loader import() call

### ISSUE THREAD

**Issue by oliverturner** [jlongster/prettier#37]
In files using  ES2015 Loader spec (e.g. bundle splitting with webpack@2.2.0-rc.3), `import(...)` throws with `SyntaxError: Unexpected token`.

This is true whether using the flow parser or babylon

Sample code: 
```jsx
import React from 'react'
import idbKeyval from 'idb-keyval'

import Shell from './components/app-shell'

class AppShell extends React.Component {
  constructor () {
    super()

    this.state = {app: <Shell />}
  }

  componentWillMount () {
    Promise.all([
      idbKeyval.get('store'),
      import('./root')
    ])
    .then(
      ([data, module]) => { this.setState({app: <module.default initialData={data} /> })}, 
      (err) => {console.log(err)}
    )
    .catch((err) => {
      console.log('Chunk loading failed', err)
    })
  }

  render () {
    return this.state.app
  }
}

export default AppShell
```

**Comment by hzoo** [comment]
this is because the babylon plugin `dynamicImport` isn't used (also on a fork of babylon atm since we haven't released)

**Comment by oliverturner** [comment]
@hzoo Just saw that myself... happy to close if it's a known quantity.

**Comment by hzoo** [comment]
Can close via https://github.com/jlongster/prettier/pull/51

**Comment by oliverturner** [comment]
Closing per this recommendation
