### ISSUE TITLE
I made a fuzz-test thingy

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#371]
Branch: https://github.com/lydell/prettier/tree/esfuzz

Using: https://github.com/estools/esfuzz/

Command: `npm run fuzz`.

It generates a random program and then runs it through prettier two times. No errors are supposed to be thrown, and the two outputs from prettier are supposed to be equal.

It prints the following:

```
<random JS>
─────────────────────────────────────
<prettier JS or parse errors or diff>
─────────────────────────────────────
<random prettier options>
─────────────────────────────────────
<message>
```

You can easily work with the results if you find something interesting:

- The random JS is written to fuzz/random.js
- The first prettier run-through is written to fuzz/prettier1.js
- The second prettier run-through is written to fuzz/prettier2.js

Example:

![screenshot from 2017-01-21 23-01-25](https://cloud.githubusercontent.com/assets/2142817/22178107/a1c910ba-e02e-11e6-96d3-bdeacffa10f6.png)

Feel free to close this if it is of no use :) I'll play around with it and see if I find anything interesting.

**Comment by vjeux** [comment]
This is awesome! Can't wait to see what you find.

If you look at run_spec.js we already have the infra to make sure that the ast before and after pretty print is the same

**Comment by vjeux** [comment]
We need to tweak the fuzzer so that missing EmptyExpressions are okay :)

![image](https://cloud.githubusercontent.com/assets/197597/22178986/ea3a1b8e-dffa-11e6-80a6-51f4f553525d.png)

**Comment by vjeux** [comment]
So great, it's finding a lot of crazy edge cases! #375 #376 #374 #373 without even trying :)

**Comment by vjeux** [comment]
I tweaked it a bit to make it more useful :) Thanks a ton for the tool!
https://github.com/lydell/prettier/pull/2

**Comment by lydell** [comment]
@vjeux I've added support for https://github.com/shapesecurity/shift-fuzzer-js now as well (enabled by default). It has ES2015 support. Let's see if it finds us anything more :)

**Comment by lydell** [comment]
I’ve now made a proper CLI tool out of the fuzzer :)
https://github.com/lydell/eslump

**Comment by vjeux** [comment]
Awesome! Thanks for all your work on it :)

Let's close this issue. Feel free to open up more bugs you find with it!

**Comment by lydell** [comment]
@vjeux You asked in some other issue if I could add random comment support to the fuzzer. Well, eslump 1.2.0, which I just released, is pretty good at generating random comments. I’ll continue tweaking the algorithm. Let’s see what it finds :)

**Comment by vjeux** [comment]
Can't wait to see all the crazy cases it finds!

**Comment by vjeux** [comment]
We should run it with https://github.com/jlongster/prettier/pull/571 patched on, this way it throws if we don't print comments we should have.
