### ISSUE TITLE
Invalid flow annotation

### ISSUE THREAD

**Issue by llimllib** [jlongster/prettier#38]
I ran prettier against our large-ish codebase, and aside from several instances of #23, I got one error:

![1 pc2 0 git - nikkisix local tmux 2017-01-10 13-06-05](https://cloud.githubusercontent.com/assets/7150/21818410/b8b083be-d735-11e6-8ab7-804f93b72abd.png)

where prettier put a colon in front of the `any`. Simply removing the colon makes it valid.

**Comment by danharper** [comment]
just for reference: this is Flow's ["optional name" syntax](https://github.com/babel/babylon/pull/197) on function types & object indexers
