### ISSUE TITLE
Missing semi-colon in strange for-loop → invalid code

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#385]
Input:

```js
for (a in b) var c = {}; [];
```

Output:

```js
for (a in b)
  var c = {}
[];
```

Trying to format the output again fails with:

```
SyntaxError: Unexpected token (3:1)
  1 | for (a in b)
  2 |   var c = {}
> 3 | [];
    |  ^
  4 | 
  5 | 
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22for%20(a%20in%20b)%20var%20c%20%3D%20%7B%7D%3B%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

Found using the fuzzer in #371.

**Comment by vjeux** [comment]
Nice find!
