### ISSUE TITLE
VS Code Plugin

### ISSUE THREAD

**Issue by zbuttram** [jlongster/prettier#39]
Would be great to have a plugin for Visual Studio Code as well. I may give it a shot if I get some free time but I'd be just as happy if someone beat me to it. :)

**Comment by jlongster** [comment]
It's good to have this issue. Ken has already started one: https://twitter.com/ken_wheeler/status/818868047758917632

Not sure where it will converge but worth reaching out to him if you want to help

**Comment by Arrow7000** [comment]
Woo, can't wait!

**Comment by rtorr** [comment]
Here was a quick go at it

https://github.com/rtorr/vscode-prettier

Still needs to be tested more.

**Comment by Arrow7000** [comment]
@rtorr that doesn't work at all.

**Comment by demoneaux** [comment]
Also: https://github.com/esbenp/prettier-vscode.

**Comment by colek42** [comment]
I have been using/contributing to this one   https://github.com/esbenp/prettier-vscode

**Comment by knowbody** [comment]
@jlongster this can be closed now, as there is https://github.com/esbenp/prettier-vscode and also the one that Ken is working on

**Comment by rtorr** [comment]
@arrow7000 it does work while debugging, but as I was at work, and suggested, it still needs some testing.

**Comment by rtorr** [comment]
I might depreciate since the other option looks complete

**Comment by rtorr** [comment]
@arrow7000 it does work. You just have to put prettier.updateOnSave to true.

**Comment by rtorr** [comment]
It is now deprecated https://github.com/rtorr/vscode-prettier
