### ISSUE TITLE
CJK characters are escaped to ASCII strings

### ISSUE THREAD

**Issue by FallenMax** [jlongster/prettier#417]
**Description:** 
prettier escapes CJK characters in string literals to ascii, making generated code unreadable

**Step To Reproduce:**  
![prett](https://cloud.githubusercontent.com/assets/2012170/22189106/7a072d64-e155-11e6-9e1f-62f88bbc6a05.png)

**Expected:**
`const text = '请求失败'`  stay un-escaped

**Actual:** 
CJK characters are escaped as ascii string, making code unreadable 

this issue should be relevant to #163,

**Comment by vjeux** [comment]
See https://github.com/jlongster/prettier/issues/163#issuecomment-274382761 :)

**Comment by FallenMax** [comment]
@vjeux Thanks (this is FAST :smile: )
