### ISSUE TITLE
Prettier escapes unicode in strings and object

### ISSUE THREAD

**Issue by vasa-chi** [jlongster/prettier#431]
Input:
```js
let unicode = "привет";
let whatever = {
  key: "привет"
};
let jsx = <div data-whatever="привет" />;
```
Output:
```js
let unicode = "\u043F\u0440\u0438\u0432\u0435\u0442";
let whatever = { key: "\u043F\u0440\u0438\u0432\u0435\u0442" };
let jsx = <div data-whatever="привет" />;
```
Example:
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22let%20unicode%20%3D%20%5C%22%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82%5C%22%3B%5Cnlet%20whatever%20%3D%20%7B%5Cn%20%20key%3A%20%5C%22%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82%5C%22%5Cn%7D%3B%5Cnlet%20jsx%20%3D%20%3Cdiv%20data-whatever%3D%5C%22%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82%5C%22%20%2F%3E%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D
Affected version: 0.0.10

**Comment by rhengles** [comment]
See #417 #163 :)

**Comment by vasa-chi** [comment]
Oh. I only searched through open issues :)
Waiting on 0.0.11 then.
