### ISSUE TITLE
Behaviour of function return changes with inline comments and parentheses

### ISSUE THREAD

**Issue by Joezo** [jlongster/prettier#432]
Hey team behind prettier, you're awesome. This tool is greatly needed!

I tried to use prettier on our `src` dir and noticed it broke a test. Working through this we found it had changed the behaviour of one method in an odd way. 

Given a function that returns multiline JSX and a strategically placed comment, running through prettier changes the function to no longer return anything.

```javascript
function doesNotReturnJSX() {
  return ( // This comment stops this function from returning
    <div>
      <span>Goodbye cruel world</span>
    </div>
  )
}
```
Prettier converts this to:
```javascript
function doesNotReturnJSX() {
  return // This comment stops this function from returning
  (
    <div>
      <span>Goodbye cruel world</span>
    </div>
  );
}
```

You can see that because the value is no longer on the same line as the return keyword, it does not get returned. 
I have simplified this to a method that returns a string, to reduce the complication of JSX, in the following test case
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20returnsAString()%20%7B%5Cn%5Ctreturn%20(%5Cn%20%20%20%20%5Ct'a%20string'%5Cn%20%20%20%20)%3B%5Cn%7D%5Cn%5Cnfunction%20doesNotReturnAString()%20%7B%5Cn%5Ctreturn%20(%20%2F%2F%20this%20comment%20stops%20this%20function%20from%20returning%5Cn%20%20%20%20%5Ct'a%20string'%5Cn%20%20%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Atrue%7D%7D

I've pushed a branch up to a fork containing what I *think* is a test case for this, being unfamiliar with this test workflow I can't be sure it's correct. Let me know if you'd like me to open it as a PR.
https://github.com/jlongster/prettier/compare/master...Joezo:function-return-comment-issue

p.s. I've tried to find out whether this is an existing issue and couldn't find anything so sorry if it's a duplicate!

**Comment by jlongster** [comment]
This is being handled in #275. Makes sense that you couldn't find that bug as it's a meta bug. We're doing a big pass at comments which will fix many of these issues. Thanks for reporting!
