### ISSUE TITLE
Incorrectly transforms flow function type declarations inside an object type alias.

### ISSUE THREAD

**Issue by SawyerHood** [jlongster/prettier#438]
Prettier currently formats flow function type declarations nested in an object declaration incorrectly for example:
`type Props = {
  className: string,
  dispatch: (action: Action) => void,
};`

becomes 

`type Props = {
  className: string,
  dispatch(action: Action): void,
};`

Which is not a valid type declaration.

**Comment by danharper** [comment]
That is valid, it's an alternate method syntax. #310 proposes using the arrow syntax instead though.

**Comment by vjeux** [comment]
Yeah, the plan is to use the first way as the canonical way. Unfortunately, the AST is constructed in a very weird way so it's not simple to do, but we'll get to it!

Closing as it is already tracked by #310, thanks for raising it!
