### ISSUE TITLE
Support shebang line

### ISSUE THREAD

**Issue by focusaurus** [jlongster/prettier#44]
My node scripts with an initial shebang line `#!/usr/bin/env node` are getting converted to `///usr/bin/env node`. These lines should be output unchanged in the formatted code.

**Comment by jlongster** [comment]
Ah, haha, yes definitely.

**Comment by k3rmitt** [comment]
When writting the test, my first issue is that flow parser wiped out the shebang.
As run_specs.js forces the use of flow parser, the result between the command line and the jest tests are not consistant. Shouldn't we test the presence of @flow to select the parser?
