### ISSUE TITLE
<strong> inside <p> is broken

### ISSUE THREAD

**Issue by magnusheino** [jlongster/prettier#444]
My .js-file is longer, but this small example shows the problem:

```js
      <p>
        Welcome to the <strong>Universal React Starter-kyt</strong>.
        This starter kyt should serve as the base for an advanced,
        server-rendered React app.
      </p>
```

turns into

```js
<p>
  Welcome to the{" "}
  <strong>Universal React Starter-kyt</strong>
  .
        This starter kyt should serve as the base for an advanced,
        server-rendered React app.
</p>;
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20Welcome%20to%20the%20%3Cstrong%3EUniversal%20React%20Starter-kyt%3C%2Fstrong%3E.%5Cn%20%20%20%20%20%20%20%20This%20starter%20kyt%20should%20serve%20as%20the%20base%20for%20an%20advanced%2C%5Cn%20%20%20%20%20%20%20%20server-rendered%20React%20app.%5Cn%20%20%20%20%20%20%3C%2Fp%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
Wow, that's surprising! I'll try to take a look later today

**Comment by rattrayalex** [comment]
Ohhh it's probably because there are multiple newlines in a single JSXText... Needs to be handled

**Comment by rattrayalex** [comment]
fixed in https://github.com/jlongster/prettier/pull/455 though I might try to add more to that PR

**Comment by rattrayalex** [comment]
#455 is ready for review, and also adds support for extra newlines between jsx elems / text lines!
