### ISSUE TITLE
Sourc

### ISSUE THREAD

**Issue by dazinator** [jlongster/prettier#445]
Am I right in thinking that sourcemap support wouldn't really make sense for this project as I'd assume if using sourcemaps (e.g to map back to original typescript etc) then you probably shouldn't bother formatting the js as it won't have any benefit?

Just throwing this out there in case anyone can see a benefit for sourcemap support that I can't.

**Comment by vjeux** [comment]
Right now prettier doesn't support sourcemaps but it should be possible to without too much trouble given the way the project is setup.

However, the performance is a concern and we don't have any concrete use cases yet.

I'm goibg to close this issue as this is not actionable but feel free to keep commenting on it
