### ISSUE TITLE
Globs not working as expected in npm scripts, but work fine from CLI

### ISSUE THREAD

**Issue by pdehaan** [jlongster/prettier#451]
Found in `"prettier": "0.11.0"` (on mac OS Sierra and ZSH)

In our package.json, we have an npm script that looks like this:

```js
  "scripts": {
    "prettier": "prettier --single-quote --write src/**/*.js webpack.config.js",
  },
```

When I run `npm run prettier`, it gives me the following output, and only seems to be checking 3 files:

```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier --single-quote --write src/**/*.js webpack.config.js

src/lib/log.js
src/webextension/background.js
webpack.config.js
```

However, I have about 5 *.js files in src/**:

```sh
$ find src | grep ".js$"

src/index.js
src/lib/log.js
src/webextension/background.js
src/webextension/survey/lib/open.js
src/webextension/survey/survey.js
```

Oddly, if I run the `prettier` command from the local ./node_modules/.bin/prettier symlink directly, it parses all files:

```sh
$ ./node_modules/.bin/prettier --single-quote --write src/**/*.js webpack.config.js

src/lib/log.js
src/webextension/background.js
webpack.config.js
src/index.js
src/webextension/survey/lib/open.js
src/webextension/survey/survey.js
```

**Comment by rhengles** [comment]
Try quoting your paths:

`$ ./node_modules/.bin/prettier --single-quote --write 'src/**/*.js' webpack.config.js`

**Comment by lydell** [comment]
Yes, quoting the glob is the way to go (letting prettier handle the globbing rather than whatever shell happens to be used in different circumstances). See https://github.com/jlongster/prettier/issues/362#issuecomment-274250544 for a longer explanation.
