### ISSUE TITLE
Suboptimal binary + operator formatting 

### ISSUE THREAD

**Issue by llimllib** [jlongster/prettier#46]
This strikes me as a really ugly format:

```
$ echo "lots + of + additions + are + put + into + some + weird + format + thats + ugly > 0" > /tmp/test.js && prettier /tmp/test.js
lots + of + additions + are + put + into + some + weird + format + thats +
  ugly >
  0;
```

Better would be:

```
lots + of + additions + are + put + into + some + weird + format + thats +
  ugly > 0;
```

Do you agree, or is this intentionally the format used by prettier?

**Comment by jlongster** [comment]
That's not intentional, and is ugly. Binary operators are a bit difficult to get right. We can play with this.

**Comment by jlongster** [comment]
@llimllib what format do you think we should do? Either:

```
lots + of + additions + are + put + into + some +
  weird + format + thats + ugly + 0;
```

```
lots +
  of +
  additions +
  are +
  put +
  into +
  some +
  weird +
  format +
  thats +
  ugly +
  0;
```

**Comment by rattrayalex** [comment]
(I'm following along the livestream) 

I vote for #2, especially for LogicalExpressions. They can often look like this: 
```
someLongCondition() ||
  this.someMethod() === someValue ||
  (somethingElseIsTrue && somethingElse === false)
```
that is, the contents of each condition are longish. 

BinaryExpressions, where you often are adding and subtracting a bunch of things (as in the example) might be different, but option 2 is a reasonable default for this case.

**Comment by llimllib** [comment]
I feel like 1) the line should be maximized, similarly to how objects are and 2) the comparison is different than the additions?

So my favorite is:

```
lots + of + additions + are + put + into + some + weird + format + thats + 
  ugly > 0;
```

and I don't at all mind:

```
lots + of + additions + are + put + into + some +
  weird + format + thats + ugly + 0;
```

I'm not a big fan of, but I could tolerate:

```
lots +
  of +
  additions +
  are +
  put +
  into +
  some +
  weird +
  format +
  thats +
  ugly > 0;
```

But I really hate

```
lots +
  of +
  additions +
  are +
  put +
  into +
  some +
  weird +
  format +
  thats +
  ugly >
  0;

**Comment by rattrayalex** [comment]
Yeah, what does this look like when mixing LogicalExpressions and BinaryExpressions, and mixing operators of varying precedence?

**Comment by jlongster** [comment]
Let's consolidate fixing binary/logical operators in #89. I'm working on this now.

**Comment by jlongster** [comment]
@llimllib check out https://github.com/jlongster/prettier/pull/262. Unfortunately right now the PR implements the option you hate most. It's a big refactoring though so I'd like to land at least this right now. There are some very tricky rules getting this to work.

I'd like to follow-up and see if we can get a better style, but this gives us better grounding.

**Comment by jlongster** [comment]
Heck, with a quick hack I was able to implement something like this: 

```js
  var z = 1 + 2 + 3 * (4 * 5 + 3) / (100000000000000000 * 328233872942374 +
      3423942394239) + 2343242342342343 + 10000;
```

I will follow-up in the PR.
