### ISSUE TITLE
Inserting space before comma in objects with non-trivial value

### ISSUE THREAD

**Issue by joefiorini** [jlongster/prettier#461]
It seems when I have an object with a key pointing to a non-trivial value and am using trailing commas, prettier inserts a space before the comma. Since it does not insert a space before commas normally, I assume this is a bug. FWIW, I couldn't reproduce on the live editor linked from this github repo (which appears to be based on the last release), so I'm assuming this is a recent problem introduced in master.

I created a failing spec here: https://github.com/joefiorini/prettier/blob/space-before-trailing-comma/tests/trailing_comma/object.js. I took a stab at making it pass, but don't have time atm to wrap my head around how it all works.

**Comment by vjeux** [comment]
Thanks! I can reproduce, looking into it.

```js
const a = {
  b: true,
  c: {
    c1: 'hello'
  },
  d: false
};

const aLong = {
  bHasALongName: 'a-long-value',
  cHasALongName: {
    c1: 'a-really-long-value',
    c2: 'a-really-really-long-value',
  },
  dHasALongName: 'a-long-value-too',
  eHasABooleanExpression: a === a,
};
```

turns into

```js
const a = { b: true, c: { c1: "hello" }, d: false };

const aLong = {
  bHasALongName: "a-long-value",
  cHasALongName: {
    c1: "a-really-long-value",
    c2: "a-really-really-long-value",
  },
  dHasALongName: "a-long-value-too",
  eHasABooleanExpression: a === a , // <----
};
```

**Comment by vjeux** [comment]
> I took a stab at making it pass, but don't have time atm to wrap my head around how it all works.

If you know it's been introduced by commits after 0.11.0, the usual best way is to bisect and figure out which commit introduced the bug. Then it's way easier to figure out what's going on.

**Comment by vjeux** [comment]
```js
409d4b6eb541ab51f42817ca759e175c752a93cc is the first bad commit
commit 409d4b6eb541ab51f42817ca759e175c752a93cc
Author: Davy Duperron <yamafaktory@gmail.com>
Date:   Tue Jan 24 20:20:24 2017 +0100

    Ability to break on `:` for objects (#314)
```

**Comment by joefiorini** [comment]
@vjeux thanks, didn't think about bisecting for some reason. Good find!

**Comment by vjeux** [comment]
https://github.com/jlongster/prettier/pull/463 fixes it!

**Comment by joefiorini** [comment]
Dang, that was fast, thanks!

**Comment by yamafaktory** [comment]
Sorry for the regression induced by my PR!

**Comment by vjeux** [comment]
@yamafaktory no worries, thankfully @joefiorini caught it really quickly :)

**Comment by vjeux** [comment]
Now we have a test so it won't regress again!
