### ISSUE TITLE
Trailing comma in function call

### ISSUE THREAD

**Issue by DWMiller** [jlongster/prettier#477]
```
  db.find(
    {
      type: 'NEW',
      $where() {
        return this.time > DAY_AGO;
      },
    },
    function() {
    }
  );
```
Becomes
```
  db.find(
    {
      type: 'NEW',
      $where() {
        return this.time > DAY_AGO;
      },
    },
    function() {
    },
  );
```

Note the comma trailing the final function, which is the final parameter in a function call, so a syntax error.

**Comment by DWMiller** [comment]
Note: Obviously avoidable if you disabled trailing commas, but I've had this come up a few times when enabled, seems to only happen when the previous arguments split into multi-line.

**Comment by vjeux** [comment]
Thanks for flagging this. There is a discussion about it on another issue: https://github.com/jlongster/prettier/issues/266

I'm going to close this one to consolidate
