### ISSUE TITLE
Parentheses preventing automatic semicolon insertion get wrongly removed

### ISSUE THREAD

**Issue by hu9o** [jlongster/prettier#480]
```javascript
function getInscrutableValue(config) {
  return (
    // this constant needs some explaining
    42
  );
}
```
turns to:
```javascript
function getInscrutableValue(config) {
  return // this constant needs some explaining
  42;
}
```

I'm not sure what output is to be expected... As hoisting comments to the upper line seems to be outside the scope of a prettifier (although it could be argued otherwise?), leaving the parentheses untouched is probably the best course of action.

*PS: While this edge-case might seem contrived, I actually ran into it when prettifying real code! (the returned expression was complex enough to justify adding comments in-between)*

**Comment by vjeux** [comment]
Hey @hu9o thanks for reporting it! It's actually a known bug where comments placement can generate invalid code like the one you showed above. We are working on a big overhaul of the way comments are implemented which should fix it. https://github.com/jlongster/prettier/issues/275

I'm going to close this as it is a duplicate.
