### ISSUE TITLE
Comment between if/else is formatted strangely

### ISSUE THREAD

**Issue by jlongster** [jlongster/prettier#487]
```js
if(x) {
}
// comment
else {
}
```

output:

```js
if (x) {
} else
  // comment
  {
  }
```

**Comment by vjeux** [comment]
I'm wondering what it should look like. Do we want to preserve the way it was originally written?

Or

```js
if (x) {
} else {
  // comment
}
```

**Comment by rafayepes** [comment]
Another alternative:


```javascript
if (x) {
} else { // comment
}
```

**Comment by yamafaktory** [comment]
@rafayepes I think we need to keep comments in-between in order to be able to handle _one-liner_ if/else (which is valid JS):

```js
if (x) something
// comment
else something_else
```

**Comment by vjeux** [comment]
Right now, this is attached as a leading comment of the block statement.

**Comment by yamafaktory** [comment]
@vjeux Yup, I saw that when trying to wrap my mind around it. I came to the point that something is missing to handle that case, a new function maybe (addLeading, addTrailing, addDangling, ?) ?

**Comment by jlongster** [comment]
I don't think there's a good generic name for this type of thing; at this point any fixes like this are likely to be specializations to that specific node. For example, when printing comments in an `if` node, we might have to specifically filter out comments that exist after the `if` block and before the `else` block and print them specially. There are likely only a few key places we'll have to do this to support common styles.

**Comment by yamafaktory** [comment]
Ok, I may have something working... will create a PR in a few minutes.

**Comment by jlongster** [comment]
I'm very tempted to do what @rafayepes suggests. It seems odd that you can inject comments and "stop" our styling rules. Normally we enforce this:

```js
if() {
} else {
}
```

So it seems only natural do move them inside the block. It seems like a good place to enforce a consistent place for comments that are documenting the `else` conditions. Also, we want to implement the same behavior for all statements that have alternate blocks like try/catch.

It also removes the need for too much special-casing in our code. As long as we move the comment to the right place, it will "just work" :)

If we are OK with that, here's what I propose:

* In the code that handles leading comments in `attach`, we can check if there is any syntax between the comment and the `followingNode`. There is already code in `breakTies` that does this. This works because the `else` syntax sits between the comment and the block's `{`, so we know something special is going on.
* If that's the case, and the `followingNode` is a block, then we attach a leading comment to the first node inside the block instead. This moves the comment inside the block.

That's a bit more generic than special-casing `if` and will work for the `catch` statement of try/catch as well. Unfortunately it makes the comment code even more complicated, but I guess we need to do it.

**Comment by yamafaktory** [comment]
Great approach, looks good to me! But what about inlined if-else?

```js
if (a) doSomething();
// comment
else doSomethingElse();
```

In this case, do you also want to enforce if-else as blocks (then always moving the comments in the block is the best option)?

**Comment by jlongster** [comment]
That already looks pretty good:

```js
if (a)
  doSomething();
else
  // comment
  doSomethingElse();
```

Basically, it forces it to break, if people really want to avoid blocks. I prefer enforcing blocks but not sure I want to do that in this project. Hard to say when we should enforce something or not.
