### ISSUE TITLE
Unecessary splitting equality check

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#503]
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%20%20const%20isPartOfPackageJSON%20%3D%20dependenciesArray.indexOf(dependencyWithOutRelativePath.split('%2F')%5B0%5D)%20!%3D%3D%20-1%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

This equality check should probably be 

```js
  const isPartOfPackageJSON = dependenciesArray.indexOf(
    dependencyWithOutRelativePath.split('/')[0],
  ) !== -1;
```

instead of 
```js
  const isPartOfPackageJSON = dependenciesArray.indexOf(
    dependencyWithOutRelativePath.split('/')[0],
  ) !==
    -1;
```

**Comment by vjeux** [comment]
I agree this is an unfortunate way of printing things. I'm not really sure how to fix it though. The way prettier works is by breaking on the outer expression first (here `!==`) and then breaking on individual expressions. It worked as "intended".

**Comment by lydell** [comment]
Well, this particular case can easily be changed to be prettier:

```js
const isPartOfPackageJSON = dependenciesArray.includes(
  dependencyWithOutRelativePath.split('/')[0]
);
```

```js
const firstSegment = dependencyWithOutRelativePath.split('/')[0];
const isPartOfPackageJSON = dependenciesArray.indexOf(firstSegment) !== -1;
```

¯\\\_(ツ)\_\/¯
