### ISSUE TITLE
Trailing comma after rest properties 

### ISSUE THREAD

**Issue by umidbekkarimov** [jlongster/prettier#507]
See https://github.com/eslint/espree/issues/310

Input
```javascript
const{foo,bar,...rest}=baz;
```

Expected
```javascript
const {
  foo,
  bar,
  ...rest
} = baz;
```

Actual
```javascript
const {
  foo,
  bar,
  ...rest,
} = baz;
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%7Bfoo%2Cbar%2C...rest%7D%3Dbaz%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A20%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks, I will fix it!

**Comment by vjeux** [comment]
#512 fixes it
