### ISSUE TITLE
Add option to exit on first error

### ISSUE THREAD

**Issue by umidbekkarimov** [jlongster/prettier#508]
Aka `--bail` in `webpack`

Currently if any error occur during execution of `prettier` it just changes `process.exitCode` and it's ok in 99% of cases, but sometimes when errors like #501 occur, it's really helpful to exit on first error and display it.

```bash
prettier --write --bail 'src/**/*.js'
````

**Comment by vjeux** [comment]
I'm not really sure how you would make it work with errors like #501, it didn't actually trigger an error from prettier perspective, it printed just fine.

**Comment by umidbekkarimov** [comment]
I noticed this #501 problem on second run :), and didn't notices status code 2, eslint show me an error.

**Comment by umidbekkarimov** [comment]
As i said here https://github.com/jlongster/prettier/pull/510#issuecomment-275931589 process exit can lead to unpredictable behavior, so I'm closing this issue.
