### ISSUE TITLE
Mixed operators code breaking

### ISSUE THREAD

**Issue by sonaye** [jlongster/prettier#514]
version: 0.13.1

original code:
![screen shot 2017-01-29 at 9 00 39 pm](https://cloud.githubusercontent.com/assets/23000873/22406552/2f1991aa-e666-11e6-8eee-fc6a07734034.png)

formatting error: 
![screen shot 2017-01-29 at 9 02 47 pm](https://cloud.githubusercontent.com/assets/23000873/22406574/52aadcc8-e666-11e6-9ec2-68dda1378fc3.png)

how it should look like:
![screen shot 2017-01-29 at 9 01 14 pm](https://cloud.githubusercontent.com/assets/23000873/22406562/3c4880e8-e666-11e6-9f63-26fb2e9c7438.png)

**Comment by vjeux** [comment]
Thanks for the report and sorry about this! There's a PR for a fix in https://github.com/jlongster/prettier/pull/502. I'm going to close it down as it's already being tracked by https://github.com/jlongster/prettier/issues/501
