### ISSUE TITLE
Comment moved to its own line

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#523]
Input:

```js
a // comment
b
```

Output:

```js
a;
// comment
b;
```

Expected:

```js
a; // comment
b;
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22a%20%2F%2F%20comment%5Cnb%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is really weird, it only seems to be happening if it's the first line of the file and there's something after.

```js
a // comment
```

```js

a // comment
b
```

```js
function f() {
  a // comment
  b
}
```

all work as expected.

**Comment by vjeux** [comment]
It seems like there are a lot of bugs with comments still around. Do you think that you could adapt your fuzzer to add comments are random places as well to harden this part of the codebase?

**Comment by lydell** [comment]
I actually added rudimentary random comment support to [eslump](https://github.com/lydell/eslump) yesterday :) However, the implementation is a hack. I plan to do it in a proper way soon.

**Comment by vjeux** [comment]
Okay, so the issue here only happens when the comment is on the first line of the file.

```js
const isStartOfFile = comment.loc.start.line === 1;
if ( ... || isStartOfFile ) {
  if (followingNode) {
  // Always a leading comment.
  addLeadingComment(followingNode, comment);
```

**Comment by vjeux** [comment]
It turns out that we don't even output comments for files that just have comments with the flow parser:

```js
>> echo '/* vjeux */' | ./bin/prettier.js
/* vjeux */
>> echo '/* vjeux */' | ./bin/prettier.js --parser flow

>>
```
