### ISSUE TITLE
Lost blank line because of comment

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#526]
Input:

```js
function a() {
  const a = 5; // ms

  return a;
}
```

Output:

```js
function a() {
  const a = 5; // ms
  return a;
}
```

Expected:

```js
function a() {
  const a = 5; // ms

  return a;
}
```

(Remove the comment and the empty line will be preserved.)

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20a()%20%7B%5Cn%20%20const%20a%20%3D%205%3B%20%2F%2F%20ms%5Cn%5Cn%20%20return%20a%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
#535 fixes it
