### ISSUE TITLE
Too many blank lines at EOF after directive

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#527]
Input:

```js
'use strict';
```

Output:

```js
"use strict";


```

Expected:

```js
'use strict';
```

In the online demo, try pressing Enter after the semicolon and watch what happens on the right: It stabilizes on three empty lines at the end.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%27use%20strict%27%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by STRML** [comment]
Seemingly related; a semicolon is added a comment at EOF if [only a directive is present](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22'use%20strict'%3B%5Cn%5Cn%2F%2F%20comment%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D).
