### ISSUE TITLE
[regression] bracket spacing not working

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#528]
Worked in 0.11.0
```
$ npm install -g prettier@0.11.0
$ echo "[ 's' ] " | prettier --bracket-spacing --stdin
[ "s" ];
```

But not after
```
$ $ npm install -g prettier@latest
$ echo "[ 's' ] " | prettier --bracket-spacing --stdin
["s"];

**Comment by amasad** [comment]
Git bisected and found the commit which turns out is not a regression: e13bb7dbba5b9b725338f19cc196f75201b9fc82

@vjeux wrote:

>    Given the discussion on #296, it seems like there's debate between spaces around `{}` but no one puts spaces around `[]`. So changing the behavior to respect this.

However the documentation doesn't match this so I'm closing this in favor of PR that updates the docs.

**Comment by lydell** [comment]
(Also, FYI, `--bracket-spacing` is on by default. (Use `--no-bracket-spacing` to turn it off.))
