### ISSUE TITLE
JSX ternaries with parens indent oddly

### ISSUE THREAD

**Issue by suchipi** [jlongster/prettier#53]
I often use parens with JSX ternaries to align opening and closing blocks, so that each "if" or "child" indentation is just one more indentation level deep:
![](https://puu.sh/thOe7/bb60466c91.png)

prettier, like many AST-based JSX formatters, strips the parens and moves the opening tag of each JSX element up to where the paren was, which looks weird:
![](https://puu.sh/thOlN/38ca2039f6.png)

**Comment by jlongster** [comment]
Yep, I'm not sure if we'll get it 100% to the original example, but I agree that it looks better. JSX still needs several tweaks.

**Comment by suchipi** [comment]
It's a bit difficult AST considering parens as their own node (which they aren't syntactically). But maybe we could try to detect this case in situations where it's most common, like ternaries, arrow function expressions, etc.

Here's an example of it in arrow function expressions:
```jsx
<Something>
  {() => (
    <SomethingElse>
      <span />
    </SomethingElse>
  )}
</Something>
```

prettier currently outputs:
```jsx
<Something>
  {() => <SomethingElse>
      <span />
    </SomethingElse>}
</Something>;
```

**Comment by vramana** [comment]
This is closely related to #73. So I am closing this in favour of that issue. You can file a new bug or reopen this if the problem still exists after that issue is solved.
