### ISSUE TITLE
Line terminators

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#537]
http://www.ecma-international.org/ecma-262/7.0/index.html#sec-line-terminators

> | Code   Point | 	Unicode Name | 	Abbreviation
> | -------------|---------------|--------
> | U+000A | 	LINE FEED (LF) | 	`<LF>`
> | U+000D | 	CARRIAGE RETURN (CR) | 	`<CR>`
> | U+2028 | LINE SEPARATOR | 	`<LS>`
> | U+2029 | 	PARAGRAPH SEPARATOR | 	`<PS>`
>
> ...
>
> ```
>  LineTerminatorSequence::
>     <LF>
>     <CR>[lookahead ≠ <LF>]
>     <LS>
>     <PS>
>     <CR><LF>
> ```

(In practice these days, everyone uses `\n`/`<LF>` except Windows which uses `\r\n`/`<CR><LF>`.)

It seems like prettier sometimes assumes that `\n`/`<LF>` is the only newline. We need to grep through the code base and fix those cases.

A question is _how_ it should be fixed. Use utility functions everywhere? It's easy to forget, though, and add new places of `.indexOf('\n')` and similar in the future. Another idea is to replace all other newlines before parsing: `text.replace(/\r\n|[\r\u2028\u2029]/g, '\n')`.

**Comment by hawkrives** [comment]
At one point, it seems like prettier just converted everything to LF: see https://github.com/jlongster/prettier/issues/92.

**Comment by lydell** [comment]
@hawkrives That issue was about the _output_ of prettier. (prettier should continue to always output only `\n` unless `\r\n` is detected). This issue is about the _input_ to prettier.

**Comment by hawkrives** [comment]
I figured it might affect considerations of the last idea, of just replacing before parsing. I (somehow) forgot that the printer was independent of the input format. Apologies.

**Comment by vjeux** [comment]
I don't think that we should handle anything except for \r and \r\n. For those two, we should have good support, if something is broken, please report an error and we'll fix it. The big things are:

- Detecting new lines: https://github.com/jlongster/prettier/blob/master/src/util.js#L167
- Printing line endings is based on the type of the first one on the file: https://github.com/jlongster/prettier/blob/master/index.js#L12
- We have places like shebang where do manually deal with it: https://github.com/jlongster/prettier/blob/master/index.js#L67

Looks like there's a few places where we only consider \n in the printer https://github.com/jlongster/prettier/blob/master/src/printer.js that we need to fix (search for \n)

**Comment by vjeux** [comment]
Cool, thanks a lot for the detective work on this :)

**Comment by lydell** [comment]
Just for future reference:

> Normalizing `\r`, `\u2028` and `\u2029` to either `\n` or `\r\n` is a thing that prettier _could_ do, but I guess it's not worth it.

This statement is wrong. prettier already does exactly this normalization. And it leaves all line terminator characters inside strings alone as it should.
