### ISSUE TITLE
Trailing comma added after comment in call expression

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#538]
This should be in the same general area of #530:

```js
foo({}
  // Hi
);
```

```js
foo(
  {}
  // Hi,
);
```

**Comment by amasad** [comment]
Also in object expressions:

```
return {
   state,
   // Hi
};
```

```
return {
   state
   // Hi,
};
```

**Comment by vjeux** [comment]
Looks like the same issue that @STRML reported in the comment of #527

**Comment by amasad** [comment]
@vjeux what makes comments so tricky?

**Comment by vjeux** [comment]
Comments can be added anywhere and are not part of the ast. Also end of line comment void everything after and can generate invalid code in the process.

Good thing is that we're close to have them handled correctly. The base we have is pretty robust, now we need to go through the edge cases.

But we only had comments properly supported last friday so it's pretty good, most of the reported issues are relatively minor and just require tweaks at this point and not big overhaul.

**Comment by heyimalex** [comment]
Pretty sure this is the same issue, but with trailing commas enabled:

```javascript
let example = [
  'FOO',
  'BAR',
  // 'BAZ',
];
```

```javascript
let example = [
  "FOO",
  "BAR"
  // 'BAZ',,
];
```

**Comment by yamafaktory** [comment]
@vjeux on current master none of the aforementioned issues are reproducible.

**Comment by vjeux** [comment]
@yamafaktory this is surprising. Did you add the trailing-commas option?

It's still an issue on 0.15.0 https://jlongster.github.io/prettier/#%7B%22content%22%3A%22foo(%7B%7D%5Cn%20%20%2F%2F%20Hi%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by yamafaktory** [comment]
@vjeux my bad, didn't know about that one...

**Comment by vjeux** [comment]
The reason

```js
var example = [
  "FOO", // example
  "BAR"
];
```

works is because `// example` has a special type "line-suffix" with special logic. Otherwise if you `join(",", elements)` it would put the `,` after the `,`.
