### ISSUE TITLE
Assertion error associated with template literals and comments

### ISSUE THREAD

**Issue by tqwhite** [jlongster/prettier#539]
I get an assertion error in the attached code sample when I remove a comment or remove a template literal.  The behavior is goofy enough that made another brief video.

[http://media.genericwhite.com/video/?prettierIssue013117Number2](http://media.genericwhite.com/video/?prettierIssue013117Number2)

[prettierIssue013117Number2.zip](https://github.com/jlongster/prettier/files/743408/prettierIssue013117Number2.zip)

(note, this code is derived from a running system. It works.)

**Comment by vjeux** [comment]
Thanks a lot for the report @tqwhite, I really enjoyed the video :) I looked at the two bugs you mentioned and none of them reproduce on the latest version (0.14.1). We are moving super fast with releases, basically fixing bugs and doing releases every 2 days or so. If you could try to update to the latest version and see if you see those issues, that would be awesome. Thanks!

```js
this.persistenceFunction(`error: ${this.loggingIdString} ${response.statusCode}`, '', (err, result) => {
  var a = 1;
  // perhaps this tells the event queue to keep the event since it's has not been saved successfully
})
```

outputs

```js
this.persistenceFunction(
  `error: ${this.loggingIdString} ${response.statusCode}`,
  "",
  (err, result) => {
    var a = 1;
    // perhaps this tells the event queue to keep the event since it's has not been saved successfully
  }
);
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22this.persistenceFunction(%60error%3A%20%24%7Bthis.loggingIdString%7D%20%24%7Bresponse.statusCode%7D%60%2C%20''%2C%20(err%2C%20result)%20%3D%3E%20%7B%5Cn%20%20var%20a%20%3D%201%3B%5Cn%20%20%2F%2F%20perhaps%20this%20tells%20the%20event%20queue%20to%20keep%20the%20event%20since%20it's%20has%20not%20been%20saved%20successfully%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by tqwhite** [comment]
I forgot to look at the version number before I upgraded but, the newer version fixed the problem. Sorry I didn't think of updating before I filed the issue. I'll try to remember that in the future. Thanks for your prompt and kind attention.

**Comment by vjeux** [comment]
No worries, we're still at the beginning of the project and ship every other day, so it's moving very fast!
