### ISSUE TITLE
Wrong indentation when composing functions

### ISSUE THREAD

**Issue by ekosz** [jlongster/prettier#541]
I've noticed that prettier doesn't seem to like syntax like `compose` when the functions it is composing take really long arguments. Here's an example out of my codebase:

Input:

```js
export default compose(
  withRelay({
    fragments: {
      viewer: () => Relay.QL`fragment on Viewer {
        id
      }`,
    },
  }),
  cssModule(styles, { allowMultiple: true }),
)(Feed);
```

Output:

```js
export default compose(withRelay({
    fragments: {
      viewer: () => Relay.QL`fragment on Viewer {
        id
      }`,
    },
  }), cssModule(styles, { allowMultiple: true }))(Feed);
```

The `fragments` property has 4 spaces in front of it instead of 2 as I would expect. Is this intended behavior?

Composing small functions looks great though:

Input: 

```js
compose(
  a,
  b,
  c,
)(Foo)
```

output: 

```js
compose(a, b, c)(Foo);
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20default%20compose(%5Cn%20%20withRelay(%7B%5Cn%20%20%20%20fragments%3A%20%7B%5Cn%20%20%20%20%20%20viewer%3A%20()%20%3D%3E%20Relay.QL%60fragment%20on%20Viewer%20%7B%5Cn%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%7D%60%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D)%2C%5Cn%20%20cssModule(styles%2C%20%7B%20allowMultiple%3A%20true%20%7D)%2C%5Cn)(Feed)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the bug report, I'm on my phone right now but I think that I fixed this bug with #517. I'm on my phone right now so can't check but you can try on master or just wait for tomorrow. I'll do a release with the fix

**Comment by jlongster** [comment]
This is indeed fixed on master. The output:

```
export default compose(
  withRelay({
    fragments: {
      viewer: () => Relay.QL`fragment on Viewer {
        id
      }`
    }
  }),
  cssModule(styles, { allowMultiple: true })
)(Feed);
```

**Comment by ekosz** [comment]
Awesome! Can't wait to try the next version. Thanks for your alls hard work.
