### ISSUE TITLE
Extra paren for negative number literal

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#542]
It's a weird set of conditions that this arrises in and I can't seem to get the repro to something smaller:

```js
state = {
  // students
  hoverColumn: -1,
};
```

becomes:

```js
state = {
  // students
  hoverColumn: (
    -1
  )
};
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22state%20%3D%20%7B%5Cn%20%20%2F%2F%20students%5Cn%20%20hoverColumn%3A%20-1%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
#545 fixes it
