### ISSUE TITLE
Extra newline and indent for JSXExpressionContainer with a dangling comment

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#543]
Notice the extra indent and an extra newline.

```js
<div>
  {
    /* mimic the table layout */
  }
</div>
```

prints

```js
<div>
  {

      /* mimic the table layout */
  }
</div>;
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%5Cn%20%20%20%20%2F*%20mimic%20the%20table%20layout%20*%2F%5Cn%20%20%7D%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Weird, it didn't do that recently. If you have time, would be awesome to bisect and see what made it change.

**Comment by vjeux** [comment]
Ohh actually nevermind.


```js
<div>
  {/* mimic the table layout */}
</div>
```

prints the same way. Haven't tested the version where there's spaces around.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%5Cn%20%20%20%20%2F*%20mimic%20the%20table%20layout%20*%2F%5Cn%20%20%7D%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by CiGit** [comment]
One more which I think is relevant to this bug
```javascript
<div>
  {/* comment */
}
</div>
```
transforms to
```javascript
<div>
  {}
</div>;
```

**Comment by vjeux** [comment]
@CiGit issue has been fixed.

For the original issue, the problem is that the AST has a `JSXEmptyExpression` which the comment is being attached to instead of the parent which fucks up everything :(
