### ISSUE TITLE
Nonbreakable space html entity is converted to a space

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#547]
```
<div>&nbsp;</div>
```

prints

```
<div> </div>;
```

Which is not strictly the same thing

**Comment by vjeux** [comment]
Great catch!

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
Sweet, I'm on it 👍

**Comment by rattrayalex** [comment]
It looks like this problem occurs when using the `babylon` parser but not the `flow` parser...

**Comment by vjeux** [comment]
Flow ast: http://astexplorer.net/#/gist/934eef2920a039a30361f61405f98636/940581aa956466b325d7d7ca067ebd77f997deb3

Babylon ast: http://astexplorer.net/#/gist/934eef2920a039a30361f61405f98636/3cea399e6514387f497dace6fb9b51c55a69d018

Looks like babylon just parses it as a space...

**Comment by vjeux** [comment]
cc @hzoo

**Comment by rattrayalex** [comment]
@vjeux you already mostly solved this, I think: https://github.com/jlongster/prettier/pull/329/files

I'm expanding that and I believe I have it working.

**Comment by rattrayalex** [comment]
Should raw ascii-160 spaces be left in the code as-is, or always output as `&nbsp;`?

**Comment by rattrayalex** [comment]
@hzoo if you'd like a contribution to fix the above AST issue in babylon, I'm quite familiar with the codebase at this point and would be happy to provide a fix.

**Comment by amasad** [comment]
@rattrayalex please do, I'm happy to take a look at you PR as well

**Comment by vjeux** [comment]
Fixed by #557 and just released to 0.15.0!

**Comment by rattrayalex** [comment]
@amasad see https://github.com/babel/babel/pull/5256 and https://github.com/babel/babylon/pull/344 – they don't actually change the `value`, but that should be okay? If not, let's open a separate issue on the babylon repo

**Comment by amasad** [comment]
@rattrayalex thanks for doing this. Looks like the Babel team is on it. (I haven't been active in a while so they probably know best).
