### ISSUE TITLE
Real-world example: Odd multiline array?

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#549]
Here is an excerpt from a [brunch](http://brunch.io/) config:

```js
({
  processors: [
    require("autoprefixer", {
      browsers: ["> 1%", "last 2 versions", "ie >= 11", "Firefox ESR"]
    }),
    require("postcss-url")({
      url: url =>
        url.startsWith("/") || /^[a-z]+:/.test(url) ? url : `/static/${url}`
    })
  ]
})
```

Output:

```js
({
  processors: [require("autoprefixer", {
      browsers: ["> 1%", "last 2 versions", "ie >= 11", "Firefox ESR"]
    }), require("postcss-url")({
      url: url =>
        url.startsWith("/") || /^[a-z]+:/.test(url) ? url : `/static/${url}`
    })]
});
```

Does this look the way we want it to? I'd expect something more similar to the input.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22(%7B%5Cn%20%20processors%3A%20%5B%5Cn%20%20%20%20require(%5C%22autoprefixer%5C%22%2C%20%7B%5Cn%20%20%20%20%20%20browsers%3A%20%5B%5C%22%3E%201%25%5C%22%2C%20%5C%22last%202%20versions%5C%22%2C%20%5C%22ie%20%3E%3D%2011%5C%22%2C%20%5C%22Firefox%20ESR%5C%22%5D%5Cn%20%20%20%20%7D)%2C%5Cn%20%20%20%20require(%5C%22postcss-url%5C%22)(%7B%5Cn%20%20%20%20%20%20url%3A%20url%20%3D%3E%5Cn%20%20%20%20%20%20%20%20url.startsWith(%5C%22%2F%5C%22)%20%7C%7C%20%2F%5E%5Ba-z%5D%2B%3A%2F.test(url)%20%3F%20url%20%3A%20%60%2Fstatic%2F%24%7Burl%7D%60%5Cn%20%20%20%20%7D)%5Cn%20%20%5D%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
The issue is that both values are calls with expansion as last argument which is treated as fitting one line. We need to manually break them by doing

shouldBreak: printed.some(willBreak)
