### ISSUE TITLE
Certain ternary causes jsx to exceed line length

### ISSUE THREAD

**Issue by jimmyhmiller** [jlongster/prettier#553]
This may have been captured elsewhere. But when you have a ternary and the true case is a function with an object passed to it and the false is jsx, the jsx can exceed the line length. (not saying this is good code)

```js
true ? test({
 a: 1
}) : <div a={123412342314} b={123412341234} c={123412341234} d={123412341234} e={123412341234} f={123412341234} g={123412341234} />
```

outputs

```js
true ? test({
      a: 1
    }) : <div a={123412342314} b={123412341234} c={123412341234} d={123412341234} e={123412341234} f={123412341234} g={123412341234} />;
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22true%20%3F%20test(%7B%5Cn%20a%3A%201%5Cn%7D)%20%3A%20%3Cdiv%20a%3D%7B123412342314%7D%20b%3D%7B123412341234%7D%20c%3D%7B123412341234%7D%20d%3D%7B123412341234%7D%20e%3D%7B123412341234%7D%20f%3D%7B123412341234%7D%20g%3D%7B123412341234%7D%20%2F%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the bug report, there's something wrong going on indeed!
