### ISSUE TITLE
Strange formatting for "if" with comment on the same line

### ISSUE THREAD

**Issue by smacker** [jlongster/prettier#563]
Input:
```js
// Accept empty response
if (response.clone) { // for fetch api

} else { // for xhr

}
```

Output:
```js
// Accept empty response
if (
  response.clone // for fetch api
) {
} else { // for xhr
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20Accept%20empty%20response%5Cnif%20(response.clone)%20%7B%20%2F%2F%20for%20fetch%20api%5Cn%5Cn%7D%20else%20%7B%20%2F%2F%20for%20xhr%5Cn%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the bug report. https://github.com/jlongster/prettier/pull/561 has more discussion on this behavior.

**Comment by vjeux** [comment]
With #561 it now looks like

```js
// Accept empty response
if (response.clone) {// for fetch api
} else {// for xhr
}
```

It is much better but it looks like there's a space missing before.
