### ISSUE TITLE
Strange if condition formatting

### ISSUE THREAD

**Issue by ZeeCoder** [jlongster/prettier#567]
Is this intentional?
I would have expected all lines to start the same.

![image](https://cloud.githubusercontent.com/assets/3679506/22545367/68225302-e930-11e6-881a-292be2ecb977.png)

**Comment by vjeux** [comment]
cc @jlongster

**Comment by jlongster** [comment]
This is expected. If it's parts of the same expression but spans multiple lines, it will indent subsequent lines to make it clear. Imagine if it were a `for` statement and took 3 different expressions. Indenting them groups the expressions in many cases and to be consistent we always do that style of indentation.

**Comment by ZeeCoder** [comment]
I'm not sure about a for statement, but couldn't it be treated differently from an if?
This to me looks a lot harder to read after prettifying.

![ifjsprettierformatting](https://cloud.githubusercontent.com/assets/3679506/22560019/f045b6ea-e96a-11e6-9cc8-54ae3915e617.png)

**Comment by jlongster** [comment]
Note that the output in #604 will make the above code look like:

```js
if (
  somethinglong1 === somethinglong2 &&
  somethinglong1 === somethinglong3 &&
  (somethinglong1 === somethinglong2 &&
    somethinglong1 === somethinglong3 &&
    somethinglong1 === somethinglong2)
) {
  console.log("hi");
}
```

We will only avoid indenting the top-level expression, and expressions are kept on the same line as parens.

**Comment by ZeeCoder** [comment]
Thanks for looking into this! 👍
