### ISSUE TITLE
Flow comment syntax errors with single arg in arrow functions

### ISSUE THREAD

**Issue by frankychung** [jlongster/prettier#568]
Here are examples of Flow syntax errors using comment syntax when annotating an arrow function with a single arg. This is using Prettier v0.15.0. Link: [Playground](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20Error%5Cnconst%20beep%20%3D%20(data%2F*%3A%20Object*%2F)%20%3D%3E%20%7B%7D%5Cn%5Cn%2F%2F%20OK%5Cnconst%20beep%20%3D%20(data%2F*%3A%20Object*%2F%2C%20secondData%2F*%3A%20Object*%2F)%20%3D%3E%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Here is the pasted example from the link above for quick viewing:

Before:
``` js
// Error
const beep = (data/*: Object*/) => {}

// OK
const beep = (data/*: Object*/, secondData/*: Object*/) => {}

```

After:
``` js
// Error
const beep = data /*: Object*/ => {};

// OK
const beep = (data /*: Object*/, secondData /*: Object*/) => {};
```

The error from Flow will look something like
```
  1: const beep = data /*: Object*/ => {};
                       ^^^ Unexpected token /*:
```

**Comment by vjeux** [comment]
Thanks! This is indeed a bug. We don't check if the argument has comments in order to remove the `()`
