### ISSUE TITLE
Long line multi-var statement produces weird indentation

### ISSUE THREAD

**Issue by joakin** [jlongster/prettier#569]
Hi!

Thanks for the project, it is awesome 💛

I've been running it in some of our code bases and I found this multiline var that results in different indentation for the body of the assignment. I thought it may be a thing to improve, although I'm not sure.

**Input**
```js
function test () {
  var hiddenPropertyName = pageVisibility.getDocumentHiddenPropertyName( document ),
    visibilityChangeEventName = pageVisibility.getDocumentVisibilitychangeEventName( document );
}
```
**Output**
```js
function test() {
  var hiddenPropertyName = pageVisibility.getDocumentHiddenPropertyName(
    document
  ),
    visibilityChangeEventName = pageVisibility.getDocumentVisibilitychangeEventName(
      document
    );
}
```

**Expected output (maybe?)**
```js
function test() {
  var hiddenPropertyName = pageVisibility.getDocumentHiddenPropertyName(
      document
    ),
    visibilityChangeEventName = pageVisibility.getDocumentVisibilitychangeEventName(
      document
    );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20test%20()%20%7B%5Cn%20%20var%20hiddenPropertyName%20%3D%20pageVisibility.getDocumentHiddenPropertyName(%20document%20)%2C%5Cn%20%20%20%20visibilityChangeEventName%20%3D%20pageVisibility.getDocumentVisibilitychangeEventName(%20document%20)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
This is expected. If you just had a single variable, you wouldn't want to output:

```js
  var hiddenPropertyName = pageVisibility.getDocumentHiddenPropertyName(
      document
    );
```

If you want it to be aligned the same way, I recommend putting `var` before each variable

**Comment by joakin** [comment]
Yeah I imagined. I personally don't like multi variable var statements and would put a var per variable but there are style guides that enforce a single var per scope (like wikimedia's) so that's why that code is like that.

Another option would be declaring with var and initializing in separate assignment statements, more noisy though.

I'm closing this up, thanks for the reply! 🍪

**Comment by jlongster** [comment]
> there are style guides that enforce a single var per scope (like wikimedia's) so that's why that code is like that.

Woha, are you serious? I've never heard of that and that seems very non-standard. It would be very hard for us to handle every single edge case of formatting like that, and it's best if it stays as consistent as possible.

**Comment by joakin** [comment]
Yep, I understand.

I think the single var thing is to avoid people doing confusing things with
the var hoisting, but yeah, it happens. It is a pretty peculiar style.

Some links if you're curious:
* https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript
* https://github.com/wikimedia/eslint-config-wikimedia
