### ISSUE TITLE
Long-length import statements could wrap

### ISSUE THREAD

**Issue by ckknight** [jlongster/prettier#576]
In the example:

```js
import someCoolUtilWithARatherLongName from '../../../../utils/someCoolUtilWithARatherLongName';
```

Which is 94 characters. Given that I want to wrap at 80 characters, my subjective ideal would be

```js
import someCoolUtilWithARatherLongName
  from '../../../../utils/someCoolUtilWithARatherLongName';
```

This isn't an issue with the `import { name } from 'source'` syntax.

**Comment by vjeux** [comment]
Makes sense, shouldn't be hard to do.

**Comment by vjeux** [comment]
Okay, actually it's more trickier than I hoped. If I make the second part a group, it breaks first instead of `{}`.

**Comment by jlongster** [comment]
I would say we just let it go past the max length threshold. It's not common for the above to happen, so I don't think we should worry about it too much.

**Comment by ckknight** [comment]
It's quite common for me, @jlongster

**Comment by vjeux** [comment]
I made a fix for it :) https://github.com/jlongster/prettier/pull/590

**Comment by ckknight** [comment]
I always believed in you, @vjeux

**Comment by PavelPikat** [comment]
This is still an issue in 1.8.2:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGUJ04A1OHATwBloBzAYTOygQIF98AzHMvgDkAOgD0AZzJwAbtRoAbJpgCGMABaTpc2kqiNVGreR2LlazVJPy9Bi8dk3zRoQG4AOlBAAaEBEwwqNASyKAqEjDIvCoKEnC+AEY4KmAA1nAwxKpgqPpRMXG+ACYQYPmx8WhQcXgACsmM6CrlhSAAVhIAHgBCyWkZxCrkdLlwLZUQAK4wmNMATOO+qjg1yCA+IJg4uTAA6qhFGsgAjHMADEsCcbvJmMgwOJOVOHAAjpOoL-Uqjc1I0RVfHF0Kh7o9KhJcowFHAAIqTCDwRYgGAqBL7Q7qZBzXwPFSoBRQ1joJprOASACsG0mcQAKmiQv8CnAuFwgA

**Comment by ikatyang** [comment]
Hi @PavelPikat, please see https://github.com/prettier/prettier/issues/1954#issuecomment-306067705:

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Comment by PavelPikat** [comment]
@ikatyang Thanks for the reply. Is it possible to disable this behavior in Prettier? I have imports formatted according to our tslint rules, but Prettier reformats imports making my code fail on lint check

**Comment by ikatyang** [comment]
@PavelPikat 

You may have to:

- use [`tslint-config-prettier`](https://github.com/alexjoverm/tslint-config-prettier) to disable tslint formatting rules that conflict with Prettier.
- or use [`prettier-tslint`](https://github.com/azz/prettier-tslint) to override Prettier's format.

**Comment by PavelPikat** [comment]
For anyone else facing similar problem:

I found out that you can now configure ignores for max-line-length in tsconfig ([feature](https://github.com/palantir/tslint/pull/3099))

**Comment by merlosy** [comment]
@PavelPikat I [found ](https://palantir.github.io/tslint/rules/max-line-length/)a better option than ignoring tslint. You can add exception for specific regex.
Prettier will have the lead for managing imports and exports, since it has a [special way to deal with them](https://prettier.io/docs/en/rationale.html#imports).
```
// edit tslint.json
"max-line-length": [
     true, 
    { 
        "limit": 140, 
        "ignore-pattern": "^import |^export {(.*?)}" 
    }
],
```
