### ISSUE TITLE
Invalid syntax output when a 

### ISSUE THREAD

**Issue by nfriedly** [jlongster/prettier#578]
When prettier v0.14.1 is executed on the following code:

```js
var obj = {
  // comment here
};
```

It converts it to this, causing a syntax error:

```
var obj = {
  // comment here};
```

I use this pattern in example js files where I describe a function's options object and default values, without actually specifying any. For example:

```js
var textToSpeech = new TextToSpeechV1({
  // if left unspecified here, the SDK will fall back to the TEXT_TO_SPEECH_USERNAME and TEXT_TO_SPEECH_PASSWORD
  // environment properties, and then Bluemix's VCAP_SERVICES environment property
  //username: 'INSERT YOUR USERNAME FOR THE SERVICE HERE',
  //password: 'INSERT YOUR PASSWORD FOR THE SERVICE HERE'
});
```
 https://github.com/watson-developer-cloud/node-sdk/blob/9943a1b936e686fddc15ce17a7b8a7d1de5994b4/examples/text_to_speech.v1.js#L6

**Comment by yamafaktory** [comment]
This should be fixed in v0.15.0 https://github.com/jlongster/prettier/commit/b040be2206e489ebd816b20fd70db6fd7e49a1d9.

**Comment by nfriedly** [comment]
OK, cool. It doesn't appear to be published to npm yet(?)

**Comment by yamafaktory** [comment]
@nfriedly Weird, I don't know if this is intentional or not (@vjeux).

**Comment by vjeux** [comment]
I did everything but run `npm publish` /facepalm

**Comment by vjeux** [comment]
And, it's live

**Comment by nfriedly** [comment]
Awesome! I have Travis CI automatically published to npm for most of my projects - I can help set that up if you'd like.

**Comment by vjeux** [comment]
That would be sweet. Right now we are doing three things for releases:

1) Generate the changelog entry with all the commits
2) Rebuild the docs website
3) Publishing to npm

and

4) Running prettier on the entire codebase and sending a pull request to see what changed. But we want to soon move to a place where it's being used on every commit.

**Comment by nfriedly** [comment]
Fine a new ticket for it and tag me. I can at least help with 2 & 3 - I'm doing those a number of places, e.g. https://github.com/watson-developer-cloud/node-sdk, and we can look at the others. (I usually write my change logs manually, and I was just planning on using esling-plugin-prettier to fail the build if it wasn't already prettified ;)

**Comment by vjeux** [comment]
https://github.com/jlongster/prettier/issues/581 :)

Thanks a ton for helping out on this, it's going to make our life so much easier.

**Comment by vjeux** [comment]
I'm going to close this, as the original issue has been fixed!
