### ISSUE TITLE
Globs aren't supported?

### ISSUE THREAD

**Issue by okonet** [jlongster/prettier#58]
Running `prettier --write --single-quote src/*.js` or when using with `package.json` like this:

```json
{
  "scripts": {
    "prettify": "prettier --write --single-quote",
    "prettify:src": "npm run prettify -- src/*.js *.js",
  }
}
```

it only processes the first file that the glob pattern is resolving. In my case running `npm run prettify:src` producing the following command:

```
prettier --write --single-quote "src/getDataTransferItems.js" "src/getDataTransferItems.spec.js" "src/index.js" "src/index.spec.js" "testSetup.js" "wallaby.config.js" "webpack.config.js"
```

But only `src/getDataTransferItems.js` got processed.

**Comment by vramana** [comment]
Currently only supports one file https://github.com/jlongster/prettier/blob/master/bin/prettier#L35.

**Comment by okonet** [comment]
Not anymore ↑
