### ISSUE TITLE
Suggestion: @prettier flag

### ISSUE THREAD

**Issue by sonaye** [jlongster/prettier#582]
I think it would be helpful to provide a way to programmatically include/exclude the js files that the cli scans. Sure, we love the work prettier does, but sometimes we have some code that we simply wish not to be changed. In order to achieve that with the current setup, one would need to separate the files and place them into different folders, prettify the directory with the code meant to be prettified, then merge back the two folders. As you can see, this is not practical at all. I believe this is a common use case and it should be addressed at an initial stage.

### How can we approach this?

`// @prettier`

Similar to Flow, the cli would only format the files that include this annotation at the top of the file. This opens the door for some other features to be implemented later on, maybe `.prettierconfig` at some point? it is too early to tell at this stage of the project i think. Complexity-wise, this option takes away some of the ease that comes along with prettier, now we would have to annotate each file in our project.

Note: if this is the way to go, then this case should be addressed:
```
// @flow
// @prettier
```
or maybe combine into one line? `// @flow @prettier`, i like this one better but not sure how easy it is to implement. I think this would be a first, having to deal with multiple annotations in this fashion.

The other way that i can think of is `/* prettier-disable */`, which has similar characteristics to the previous approach. Think of Flow comments vs. ESlint comments.

Interested in hearing your thoughts on this.

**Comment by jlongster** [comment]
> I believe this is a common use case and it should be addressed at an initial stage.

This is what I disagree on. This should not be a common case at all; the whole point of this project is to force consistency. There are times when you may want an escape hatch, and that's already being discussed in #120 so we should probably move this discussion there.

**Comment by sonaye** [comment]
What is proposed in the other issue is similar to what i had in mind, something like
```/* prettier-disable */
// do stuff ..
/* prettier-enable */
```
> There are times when you may want an escape hatch

This is actually a more accurate description, exactly is what i think it should be addressed.

I have no further comments, and we can move the discussion there, feel free to close this issue.

**Comment by lydell** [comment]
@sonaye See also: #579
