### ISSUE TITLE
Keeping this.<sth> together

### ISSUE THREAD

**Issue by houshuang** [jlongster/prettier#587]
This is a diff between output of 0.14.1 and 0.15. Too me, this looks like a regression, when using this.<something>, that is the thing you are doing something to, this by itself doesn't mean much.

![screen shot 2017-02-03 at 14 14 10](https://cloud.githubusercontent.com/assets/61575/22592670/33a72774-ea1b-11e6-88f4-e55bea1665a9.png)

**Comment by jlongster** [comment]
Ping @vjeux, I think 0.15 is when we rewrote member expressions. I agree this is less pretty, but it's really hard to find a consistent way to format member lookups for all cases.

**Comment by vjeux** [comment]
Thanks for raising this issue! I do think that the previous behavior in this case is the right one and that we can make it work without any hacks.

If there the expression is of the form

a.b.c()

Then a.b is likely to be the object you are operating on, so it should be it's own group. I'll send a pr :)

**Comment by vjeux** [comment]
https://github.com/jlongster/prettier/pull/589
