### ISSUE TITLE
Class getters do not get semicolon

### ISSUE THREAD

**Issue by houshuang** [jlongster/prettier#588]
This is the output of 0.15, seems to me that all the get blocks should also be terminated by semicolon? (This is using MobX)

![screen shot 2017-02-03 at 14 16 24](https://cloud.githubusercontent.com/assets/61575/22592723/64b097a6-ea1b-11e6-9b6e-23ea56e3973e.png)

**Comment by lydell** [comment]
Getters and setters are method declarations, aren't they? Method declarations shouldn't have semicolons.

**Comment by houshuang** [comment]
You are right apparently. Thanks!
