### ISSUE TITLE
Support sending data via Stdin

### ISSUE THREAD

**Issue by sbdchd** [jlongster/prettier#59]
Example:

```
cat test.js | prettier
```

**Comment by fortes** [comment]
This has the nice side effect of allowing easy vim integration, as you can do something like:

```
autocmd FileType javascript set formatprg=prettier
```

Then you can use `gq` in order to format.

**Comment by jlongster** [comment]
Sounds good to me. Anyone want to do this?

**Comment by fortes** [comment]
I took a stab at a fix, let me know what you think.
