### ISSUE TITLE
Unstable comment – between blocks?

### ISSUE THREAD

**Issue by lydell** [jlongster/prettier#601]
```js
try {}
// comment
finally {}
```

becomes ([online demo](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22try%E2%80%86%7B%7D%5Cn%2F%2F%20comment%5Cnfinally%20%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D))

```js
try {
} finally // comment
{
}
```

becomes ([online demo](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22try%20%7B%5Cn%7D%20finally%20%2F%2F%20comment%5Cn%7B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D))

```js
try {
} finally { // comment
}
```

Found using [eslump](https://github.com/lydell/eslump). I also tried this with all of @vjeux’s PRs merged.

**Comment by vjeux** [comment]
We had to special case if then else, we should do the same trick for try catch :)
