### ISSUE TITLE
Long names cause strange line-breaks with Arrow Functions

### ISSUE THREAD

**Issue by AndruC** [jlongster/prettier#61]
I've found a strange case when using Arrow functions, chaining methods off an object inside the arrow function.
![image](https://cloud.githubusercontent.com/assets/843112/21822777/9d71faea-d746-11e6-8c3a-bd8ff0958e34.png)

If I shorten the length of the variable name
![image](https://cloud.githubusercontent.com/assets/843112/21822879/f4eca9b4-d746-11e6-9b55-fcca33828fe1.png)
or shorten the first method name
![image](https://cloud.githubusercontent.com/assets/843112/21822909/1427cfac-d747-11e6-93e0-0924c4968621.png)
then it collapses and displays more correctly. 

I also noticed that changing the name of the `otherLongfunctionName` doesn't have any effect. In either case above, both long names push the line length beyond the acceptable length. This causes the arrow function parameters to be put on a new line, even though line-breaking after `this` would lead to a better result.  IMO the "problem" examples I provided are already formatted ideally.

**Comment by jlongster** [comment]
I think you should just move it into a proper block:

```js
var oneLongVariableName = (foo, bar) => {
  return this.longerMethodName(c, service).forEach(otherLongFunctionName);
}
```

We don't really support arrow functions without blocks with code on the next line. It would be a hard special-case to format correctly without breaking other formats that involve arrow expressions.

**Comment by RamIdeas** [comment]
(Watching the twitch live stream)

I possible solution that would respect the case above, and the chains of - for example - promises, could be to align on the period, like:

```
var variable = (foo, bar) => this.methodName(...)
                                 .forEach(...);
```

```
promise.then( () => ... )
       .then( () => ... )
       .then( () => ... )
```

**Comment by rattrayalex** [comment]
I would really love to see this re-opened... cool if I try to tackle it as a first contribution? 😉

**Comment by jlongster** [comment]
@rattrayalex Sure! If I didn't just solve it, I'll leave it up to you :) I think I may have something works.

**Comment by jlongster** [comment]
Ok, let's try this. I'm curious if this causes any other awkward formatting, but I think this works.
