### ISSUE TITLE
Spurious empty line in JSX

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#614]
```js
x = (
  <div>
    <span
      className="nuclide-console-new-messages-notification-icon icon icon-nuclicon-arrow-down"
    />
    New Messages
  </div>
);
```

turns into

```js
x = (
  <div>
    <span
      className="nuclide-console-new-messages-notification-icon icon icon-nuclicon-arrow-down"
    />

    New Messages
  </div>
);
```

with an empty line before "New Messages".

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22x%20%3D%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cspan%5Cn%20%20%20%20%20%20className%3D%5C%22nuclide-console-new-messages-notification-icon%20icon%20icon-nuclicon-arrow-down%5C%22%5Cn%20%20%20%20%2F%3E%5Cn%20%20%20%20New%20Messages%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

cc @rattrayalex

**Comment by rattrayalex** [comment]
Cool I'll fix tomorrow
