### ISSUE TITLE
[JSX] - should prettier keep blank lines after opening and before closing tags?

### ISSUE THREAD

**Issue by umidbekkarimov** [jlongster/prettier#619]
Prettier removes blank lines at the start and at the end of the blocks:

In
```javascript
const func = () => {
  
  
  const foo = 1
  
  
  const bar = 2
  
  
  const baz = 3
  
  
}

if (true) {
    
  
  const foo = 1
  
  
  const bar = 2
  
  
  const baz = 3
  
  
}
```
Out
```javascript
const func = () => {
  const foo = 1;

  const bar = 2;

  const baz = 3;
};

if (true) {
  const foo = 1;

  const bar = 2;

  const baz = 3;
}
```

But keeps extra one line in case of JSX tags:

In
```javascript
const comp = (

  
<div>

  	<div>
  foo
  </div>
  
  
  
  	<div>
  bar
  </div>
  
  	<div>
  baz
  </div>
  
  </div>

)
```

Out
```javascript
const comp = (
  <div>

    <div>
      foo
    </div>

    <div>
      bar
    </div>

    <div>
      baz
    </div>

  </div>
);


```

[Example.](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20comp%20%3D%20(%5Cn%5Cn%20%20%5Cn%3Cdiv%3E%5Cn%5Cn%20%20%5Ct%3Cdiv%3E%5Cn%20%20foo%5Cn%20%20%3C%2Fdiv%3E%5Cn%20%20%5Cn%20%20%5Cn%20%20%5Cn%20%20%5Ct%3Cdiv%3E%5Cn%20%20bar%5Cn%20%20%3C%2Fdiv%3E%5Cn%20%20%5Cn%20%20%5Ct%3Cdiv%3E%5Cn%20%20baz%5Cn%20%20%3C%2Fdiv%3E%5Cn%20%20%5Cn%20%20%3C%2Fdiv%3E%5Cn%5Cn)%5Cn%5Cn%5Cnconst%20func%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%5Cn%20%20const%20foo%20%3D%201%5Cn%20%20%5Cn%20%20%5Cn%20%20const%20bar%20%3D%202%5Cn%20%20%5Cn%20%20%5Cn%20%20const%20baz%20%3D%203%5Cn%20%20%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
cc @rattrayalex I don't think that it was clearly specified when you worked on JSX support but we don't want empty lines at the beginning and end of expressions :)

**Comment by rattrayalex** [comment]
makes sense – to be clear, the desired output would be:

```jsx
const comp = (
  <div>
    <div>
      foo
    </div>

    <div>
      bar
    </div>

    <div>
      baz
    </div>
  </div>
);
```

correct?

**Comment by vjeux** [comment]
correct

**Comment by rattrayalex** [comment]
FWIW, I'd intentionally added support for that because I'd personally found it useful at times. For example (fairly contrived):

```jsx
const SomeBigWrapperComponent = (
  <SomeProvider>
    <SomeOtherProvider>
      <div className="container">
        <div className="container-inner">

          <div className="row-first">
            <FirstChild />
          </div>

          <div className="row-second">
            <SecondChild />
          </div>

          <div className="row-third">
            <ThirdChild />
          </div>
          
        </div>
      </div>
    </SomeOtherProvider>
  </SomeProvider>
);
```

**Comment by rattrayalex** [comment]
It's also worth mentioning that the general situation of 

[several block-starts in a row]
[several sibling blocks]
[several block-ends in a row]

is less likely to occur in js code than in jsx. So enforcing the no-opening-newlines and no-closing-newlines rule makes more sense in js than in jsx. 

eg; I would prefer this code: 
```js
for (i of outer) {
  for (j of inner) {
    for (k of innerer) {

      if (i === j) {
        console.log("i is j!")
      }

      if (j === k) {
        console.log("j is k!")
      }

      if (i === k) {
        console.log("i is k!")
      }
      
    }
  }
}
```

over this code:
```js
for (i of outer) {
  for (j of inner) {
    for (k of innerer) {
      if (i === j) {
        console.log("i is j!")
      }

      if (j === k) {
        console.log("j is k!")
      }

      if (i === k) {
        console.log("i is k!")
      }    
    }
  }
}
```

but that happens so infrequently in JS (fortunately) that it's not worth optimizing for. But it does happen pretty frequently in JSX.

Just my 2c (I've already committed the change to adopt this issue's proposal)

**Comment by vjeux** [comment]
Let's summon @jlongster to make the final decision on this :)

**Comment by rattrayalex** [comment]
Cool; I don't feel strongly about it, but thought I should voice the thought since it's what convinced me to write the feature.

For now, I'm assuming we'll accept the above specification and have the implementation rolled into #626 .

**Comment by jlongster** [comment]
@umidbekkarimov do you have any strong arguments for it? I view JSX as a lot more "malleable" than JS (meaning why keep much of the original formatting, but try to format it where we can).

I'm fine being more lenient on blank spaces in JSX unless there's a good argument not to.

**Comment by umidbekkarimov** [comment]
@jlongster Actually no. 

I've stated this issue as a question if it's desired behavior or not.
Few versions before prettier removed every blank line, now it keeps one, so I started looking for answers.

Personally, I treat JSX tags like JS blocks, so I try to remove extra lines every time for the sake of consistency.

**Comment by jlongster** [comment]
Ok. Let's continue keeping the spaces for now unless more people want this behavior. We usually default to being more lenient with JSX. If we see this issue again by somebody else we can implement it.
