### ISSUE TITLE
Function trailing comma

### ISSUE THREAD

**Issue by thangngoc89** [jlongster/prettier#621]
I'm using prettier integration with VS Code. When I set `prettier.trailingComma = true`, prettier add function trailing comma to the formatted code. Node 7 haven't supported this yet so I think it's better for prettier to not add function trailing comma.

**Comment by lydell** [comment]
This seems to be a duplicate of #266 :)

**Comment by thangngoc89** [comment]
@lydell  yeah. Close this. Sorry :+1:
