### ISSUE TITLE
JSX spaces are not stable

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#622]
```js
sortIndicator =
  <span> <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} /></span>;
```

turns into

```js
sortIndicator = (
  <span>
     <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} />
  </span>
);
```

which then turns into

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22sortIndicator%20%3D%5Cn%20%20%3Cspan%3E%20%3CIcon%20icon%3D%7BsortDescending%20%3F%20'triangle-down'%20%3A%20'triangle-upward'%7D%20%2F%3E%3C%2Fspan%3E%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

```js
sortIndicator = (
  <span>
    <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} />
  </span>
);
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22sortIndicator%20%3D%20(%5Cn%20%20%3Cspan%3E%5Cn%20%20%20%20%20%3CIcon%20icon%3D%7BsortDescending%20%3F%20'triangle-down'%20%3A%20'triangle-upward'%7D%20%2F%3E%5Cn%20%20%3C%2Fspan%3E%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

If you look closely, there was 3 spaces before `<Icon` and when reprinted, there's only 2.

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
Hmm, the leading space in the first example should have been transformed into `{' '}` - that's a bug. Thanks for reporting! Hope to fix today.

**Comment by rattrayalex** [comment]
This one is pretty tricky; `ifBreak('{" "}', " ")` is inside a parent which is breaking, but the group its in isn't breaking. So it's printing as a `' '` instead of a `{' '}`. 

I'll probably have to elevate the `ifBreak` to a higher group, which may get pretty ugly unfortunately 😕

**Comment by rattrayalex** [comment]
Is there a construct for breaking a child if the immediate parent breaks?

**Comment by vjeux** [comment]
Do not wrap the child in a group?

**Comment by rattrayalex** [comment]
Yep – just a bit awkward to extract in this case. Didn't end up being too bad.
