### ISSUE TITLE
Invalid comment with empty array and last argument expansion

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#624]
```js
expect(() => {}).toTriggerReadyStateChanges([
  // Nothing.
]);
```

turns into

```js
expect(() => {}).toTriggerReadyStateChanges(
  [
    // Nothing.],
);
```

which doesn't parse

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22expect(()%20%3D%3E%20%7B%7D).toTriggerReadyStateChanges(%5B%5Cn%20%20%2F%2F%20Nothing.%5Cn%5D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by prettydiff** [comment]
I see there are several issues open regarding comments.  *The best way I have bound to manage comments in a beautifier is to kind of pretend like they aren't there.*  I haven't looked at the source code yet, so forgive me if I am off-base.

1. In the lexer/parser I parse all tokens appropriately and pay close attention to syntax.  This ensures the comments are accounted for in the proper placement of the token list and are identified (or grouped correctly).  It seems you guys have nailed this part.

2. I separate out the beautifier into a separate and unrelated second step, from the lexer/parser step, in my own approach.  I am not sure if you guys do this or do it all at the same time like js-beautify.  In the beautifier I am really just populating white-space assignment: indentation level, a space, or no additional characters.  I apply this stuff into formatted output in a later unrelated third step.

3. In the beautification step I am looping through an array of tokens populated from the lexer/parser stage.  At each interval in this loop I am assigning 4 references: ctoke, ctype, ltoke, ltype.  These references really mean current token, current token type, previous token, previous token type.  I give special treatment to comments though in that I don't reassign the *ltoke* and *ltype* references if the ctype value is *comment*.  **The magic here is that if the current token needs information about the prior token to make a decision on how it should beautify it will see, from the ltoke/ltype references, the prior token isn't a comment and thus make the most correct decision every time.**

The beautifier doesn't, except in known special cases, ever need to know about relationships to comments.  This prevents comments from interfering with the evaluation and relationship of surrounding tokens.  The converse is that comments can cause recursive failures when a set of code is beautified multiple times.

When I am beautifying comments in code I only need to know 2 things, which can be evaluated before approaching the beautification step.  This is an absolute law in my beautifier.

* Whether or not to indent comments according to an option setting
* Whether or not a line comment should occur at the end of a line of code

I had to learn this the hard way and it has saved me countless headaches.
