### ISSUE TITLE
Semicolons after class properties

### ISSUE THREAD

**Issue by thezanke** [jlongster/prettier#634]
If you use babel-plugin-transform-class-properties, properties you add to classes are automatically punctuated with a semicolon by prettier. Is this intended/preferable? I've been omitting a trailing semicolon in these situations myself.

**Comment by lydell** [comment]
Yes, it is intended.

```js
class A {
  a = 1
  [b] = 2
}
```

The above actually means ([demo](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=class%20A%20%7B%0A%20%20a%20%3D%201%0A%20%20%5Bb%5D%20%3D%202%0A%7D&experimental=false&loose=false&spec=false&playground=true)):


```js
class A {
  a = 1[b] = 2
}
```

while you probably meant ([demo](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=class%20A%20%7B%0A%20%20a%20%3D%201%3B%0A%20%20%5Bb%5D%20%3D%202%3B%0A%7D&experimental=false&loose=false&spec=false&playground=true)):

```js
class A {
  a = 1;
  [b] = 2;
}
```

**Comment by thezanke** [comment]
@lydell This is good to know, thank you!

**Comment by jlongster** [comment]
Thanks for responding @lydell!
