### ISSUE TITLE
Trailing commas break for comments

### ISSUE THREAD

**Issue by mxstbr** [jlongster/prettier#637]
With this code:

```JS
var x = {
  foo: 'bar',
  // comment
}
```

and the trailing commas option `prettier` will add a comma to the comment:

```JS
var x = {
  foo: 'bar',
  // comment,
}
```

which doesn't make a lot of sense. 😉

> Note: I'd submit a failing test case, but I can't figure out how your test system works, so this'll have to do. Sorry!

**Comment by jlongster** [comment]
This is a known issue but I can't find the other issue yet. I don't see that output though; the first comma shouldn't be there:

```js
var x = {
  foo: "bar"
  // comment,
};
```

The problem is that it's adding a trailing comma to the last node but the comment was printed with that node. This might be a little tricky.

Thanks for filing!

**Comment by vjeux** [comment]
#538

Fwiw, it's easy to detect this case so we could avoid adding a trailing comma there, not ideal but at least it stops adding a comma at the end of the comment everytime you run prettier

**Comment by mxstbr** [comment]
Urg my search-fu failed me, sorry for the noise. Closing as a duplicate!
