### ISSUE TITLE
JetBrains IntelliJ IDEA: Error running Prettier

### ISSUE THREAD

**Issue by geraldfullam** [jlongster/prettier#638]
I installed prettier globally and then followed the examples for setting up Prettier as an External Tool in JetBrains IntelliJ IDEA, but when I run it I get the following error:

```
Error running Prettier:
Cannot run program "prettier" (in directory "/Users/geraldfullam/projects/prettier-test"): error=2, No such file or directory
```

Any ideas?

**Comment by geraldfullam** [comment]
Never mind. I had a failed global install. Retried and it is working.

**Comment by dortonway** [comment]
I reinstalled global prettier, but still have the issue :(
