### ISSUE TITLE
.prettierrc or other configuration file?

### ISSUE THREAD

**Issue by tmcw** [jlongster/prettier#644]
I'm interested in using prettier on a team, and we'd prefer a few options by default - single quotes, 100 or 120-char lines. As far as I can tell, the only way to supply these options is on the command line, which is doable for an npm script or for one person, but gets tricky when you have different editor plugins for different people.

Happy to help with the implementation of a configuration system, like `.prettierrc` or `.prettier.js`, that would be read from the working directory if possible.

**Comment by lydell** [comment]
I think this is a duplicate of #98 :)

**Comment by tmcw** [comment]
Indeed, sorry about the noise!
