### ISSUE TITLE
"Algebraic types" in Flow don't look nice

### ISSUE THREAD

**Issue by houshuang** [jlongster/prettier#646]
I guess this isn't very common code, but these type definitions in Flow don't look too nice - the line bginning with mode: 'moving' should probably be indented further.

<img width="577" alt="screen shot 2017-02-08 at 13 25 03" src="https://cloud.githubusercontent.com/assets/61575/22737172/2def53ca-ee02-11e6-9e6c-95001daf62de.png">

(v. 0.15.0)

**Comment by vjeux** [comment]
Good call, we should indent them a bit more :)
