### ISSUE TITLE
Prettier keeps quotes in numeric properties

### ISSUE THREAD

**Issue by umidbekkarimov** [jlongster/prettier#647]
In
```javascript
const foo = { '0': 'a', '1': 'b', '2': 'c' };
const bar = { 'a': '0', 'b': '1', 'c': '2' };
```
Out

```javascript
const foo = { "0": "a", "1": "b", "2": "c" };
const bar = { a: "0", b: "1", c: "2" };
```
Expected
```javascript
const foo = { 0: "a", 1: "b", 2: "c" };
const bar = { a: "0", b: "1", c: "2" };
```
[Example](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%20'0'%3A%20'a'%2C%20'1'%3A%20'b'%2C%20'2'%3A%20'c'%20%7D%3B%5Cnconst%20bar%20%3D%20%7B%20'a'%3A%20'0'%2C%20'b'%3A%20'1'%2C%20'c'%3A%20'2'%20%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

**Comment by s-ilya** [comment]
@umidbekkarimov  I guess there might be confusion in case of numbers like `1e1`: `foo[1e1]` and `foo['1e1']` will point to different properties.

**Comment by s-ilya** [comment]
@umidbekkarimov thus explicit conversion to string

**Comment by umidbekkarimov** [comment]
@s-ilya oh, I see, I guess it's better to reconfigure eslint then. Thanks 👍 closing.
