### ISSUE TITLE
Incorrect trailing comma?

### ISSUE THREAD

**Issue by oscar-b** [jlongster/prettier#649]
This doesn't look right?

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22let%20test%20%3D%20%7B%5Cn%20%20callbackUrl%3A%20%60https%3A%2F%2Fexample.com%2Freallylongurl%2Fwithparams%2F%24%7Bid%7D%2F%24%7BgetSomethingSecret(bookingid)%7D%60%2C%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

The trailing comma after the parameter in the function call `getSomethingSecret`

**Comment by rtsao** [comment]
See: https://github.com/jlongster/prettier/issues/266

**Comment by oscar-b** [comment]
Yup #266 seems to be the one, thanks.
