### ISSUE TITLE
Curried fat arrow functions get unexpected newline

### ISSUE THREAD

**Issue by aij** [jlongster/prettier#65]
foo(bar => {
      return qux;
    })

Is formatted as above (which seems fine), however I would expect

    foo(bar => baz => {
      return qux;
    })

rather than

    foo(
      bar => baz => {
        return qux;
      }
    );

A similar example with a const instead of a function call formats as

    const foo = bar => baz => {
      return qux;
    };

So, I have no idea why the function call is getting extra newlines.

(Granted, it would be even nicer if the unnecessary curlies and `return` were removed, but I'm guessing that is beyond the scope of this tool.)

**Comment by jlongster** [comment]
Thanks for the issue, fixed!

**Comment by im-martijn** [comment]
I have a similar issue. Using prettier 0.22.0, I get:
```
export const foo = bar =>
  baz => {
      return qux;
  };
```

Colleagues of mine use the prettier plugin in the last version of Visual Studio Code (which also uses prettier 0.22.0). This plugin gives:
```
export const foo = bar => baz => {
  return qux;
};
```

What could cause this difference? From the earlier comments in this issue, I take that the plugin in Visual Studio code is giving the correct results and my prettier version seems to be off. Is that correct? If so, how can I fix it?

**Comment by real34** [comment]
@im-martijn I had the same issues, and it seems to have been adressed as part of #1066 a few days ago (for the 0.23.0)

**Comment by martijnsenden** [comment]
Thanks!
