### ISSUE TITLE
Question: does prettier intend to support HTML files aka JS inside the script tag?

### ISSUE THREAD

**Issue by zigomir** [jlongster/prettier#651]
Would be nice for Vue or Svelte (possibly others too?)  components.

**Comment by vjeux** [comment]
Would be great to support this use case, but unsure if it's the role of prettier itself to do so or some other tool that takes html, finds the javascript parts and then calls prettier on those.

**Comment by jlongster** [comment]
Emacs has functionality that allows you to "narrow" to parts of the file. I frequently use this when working in a mixed mode file, which puts only the JS inside the buffer, and then I can press a keystroke to invoke prettier on it.

There are likely to be many different workflows for getting this to work, so I agree with @vjeux, this is out of scope for prettier itself but other tools should solve this.

**Comment by zigomir** [comment]
Ah cool, I didn't know that. It works in Atom too. Thanks!

**Comment by giodamelio** [comment]
@jlongster How do you manage that? When use `mmm-narrow-to-submode-region` to narrow to just the JS, and run `prettier` (from [prettier-emacs](https://github.com/prettier/prettier-emacs/)) it still treats it as the whole file.
