### ISSUE TITLE
Too much vertical space taken up by identations

### ISSUE THREAD

**Issue by gcazaciuc** [jlongster/prettier#653]
Currently if you have a code along the lines:

```js
import { abc, reallyLongName, anotherImport } from 'really-long-path'
```

it gets formatted to:

```js
import {
    abc,
    reallyLongName,
    anotherImport
} from 'really-long-path';
```

If you have many items imported, each one being placed on a new line, can lead to a waste of vertical space. Instead a better options would probably be to try to group on the same line as much as possible and break when printWidth is reached, eg:

```js
import {
    abc,  reallyLongName,
    anotherImport
} from 'really-long-path';
```

This applies also for function params.

**Comment by yamafaktory** [comment]
IMHO I find it quite cumbersome to put as many imports as possible per line (I never encountered something like that in any codebase). Moreover, keeping one import per line makes life easier when there's a need for refactoring.

**Comment by jlongster** [comment]
Yeah, the current style is preferred and a lot more consistent, sorry. It's OK to use vertical space to make things easier to read and refactor. We aren't going to change this, sorry!
