### ISSUE TITLE
Quotes in JSX are double quotes even if singleQuote is true

### ISSUE THREAD

**Issue by tmcw** [jlongster/prettier#656]
![image](https://cloud.githubusercontent.com/assets/32314/22802249/0bb7299a-eede-11e6-9210-679eb6bb2a6c.png)

This is replicable in the demo environment: the `singleQuote` variable works properly for vanilla JavaScript but does not affect JSX, which is always double-quotes.

**Comment by tmcw** [comment]
Whoops, https://github.com/jlongster/prettier/pull/126 explains this.

**Comment by atombender** [comment]
This was marked fixed, but I'm being hit by the same bug in 1.4.2. Is there a recent regression?

```shell
$ prettier -v
1.4.2
$ echo "<Foo bar='xyz'/>" | prettier --single-quote --stdin
<Foo bar="xyz" />;
```

**Comment by vjeux** [comment]
@atombender prettier will not honor the `--single-quote` option for JSX. This is an explicit decision and we're not looking into changing it.

**Comment by atombender** [comment]
What's the alternative? It's automatically converting my single quotes back into double quotes, so it's not like it lets me choose. Where's the discussion where I read about the rationale?

**Comment by vjeux** [comment]
Prettier is an opinionated printer, if you do not like the decisions that were made, I'm afraid that you either have to fork it to make them match the way you format code or not use prettier :(

JSX was designed to be close to HTML and people use double quote to write HTML, so are we at Facebook and a lot of people writing JSX.

**Comment by vadik49b** [comment]
This is only limitation preventing me to use Prettier together with [standard.js](https://standardjs.com/)  😞

**Comment by luftywiranda13** [comment]
@atombender @vadik49b maybe you can combine eslint and prettier to do this.

* set eslint rule [(jsx-quotes)](http://eslint.org/docs/rules/jsx-quotes)
* then run eslint --fix after prettier

**Comment by azz** [comment]
@vadik49b 
>This is only limitation preventing me to use Prettier together with standard.js 😞

There's  [prettier-standard](https://github.com/sheerun/prettier-standard), too.

**Comment by adonis-work** [comment]
I fixed this bug by running them in series from an npm script:

1. `prettier-standard` which uses prettier
2. `standard --fix` which removes all remaining bugs in the output from the previous command

**Comment by baelec** [comment]
[I created a pull-request that addresses this.](https://github.com/prettier/prettier/pull/3839) Hoping there can be room for discussion.

**Comment by initFabian** [comment]
Would I say this was really annoying... Absolutely! but ends up, I can just wrap the `string` in some curly braces and poof! its gone.


![screen shot 2018-04-25 at 2 35 41 pm](https://user-images.githubusercontent.com/8469495/39268629-fee6b006-4895-11e8-8b20-a2524fe083d8.png)
