### ISSUE TITLE
Example of unstable JSX + parentheses

### ISSUE THREAD

**Issue by kjbekkelund** [jlongster/prettier#686]
```js
function MyCompoent() {
  return (
    <div>
      (<FormattedMessage
        id="some-id"
        defaultMessage="some looooooooog default"
      />)
    </div>
  );
}
```

turns into:

```js
function MyCompoent() {
  return (
    <div>
      (
      <FormattedMessage
        id="some-id"
        defaultMessage="some looooooooog default"
      />
      )
    </div>
  );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20MyCompoent()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20(%3CFormattedMessage%5Cn%20%20%20%20%20%20%20%20id%3D%5C%22some-id%5C%22%5Cn%20%20%20%20%20%20%20%20defaultMessage%3D%5C%22some%20looooooooog%20default%5C%22%5Cn%20%20%20%20%20%20%2F%3E)%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

which turns into:

```js
function MyCompoent() {
  return (
    <div>
      (

      <FormattedMessage
        id="some-id"
        defaultMessage="some looooooooog default"
      />
      )
    </div>
  );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20MyCompoent()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20(%5Cn%20%20%20%20%20%20%3CFormattedMessage%5Cn%20%20%20%20%20%20%20%20id%3D%5C%22some-id%5C%22%5Cn%20%20%20%20%20%20%20%20defaultMessage%3D%5C%22some%20looooooooog%20default%5C%22%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20)%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

It becomes stable after adding two newlines:

```js
function MyCompoent() {
  return (
    <div>
      (


      <FormattedMessage
        id="some-id"
        defaultMessage="some looooooooog default"
      />
      )
    </div>
  );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20MyCompoent()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20(%5Cn%5Cn%5Cn%20%20%20%20%20%20%3CFormattedMessage%5Cn%20%20%20%20%20%20%20%20id%3D%5C%22some-id%5C%22%5Cn%20%20%20%20%20%20%20%20defaultMessage%3D%5C%22some%20looooooooog%20default%5C%22%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20)%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
cc @rattrayalex looks like the newline detection isn't working well for just a single (

**Comment by rattrayalex** [comment]
Wow, that's very strange. I'll take a peek tomorrow

**Comment by rattrayalex** [comment]
I'm struggling to imagine what's causing this from looking at the intermediate doc:

```
              conditionalGroup([
                [
                  "(",
                  softline,
                  group([
                    "<",
                    "FormattedMessage",
                    indent(2, [
                      line,
                      "id",
                      "=",
                      '"some-id"',
                      line,
                      "defaultMessage",
                      "=",
                      '"some looooooooog default"'
                    ]),
                    line,
                    "/>"
                  ]),
                  softline,
                  ")"
                ]
              ])
```

**Comment by rattrayalex** [comment]
Ah, no, that was silly of me. Of course it will break there. A bit unfortunate but very unlikely to be fixable without an ugly hack. 

The insertion of an extra newline is a problem, I have some ideas about what might be causing that.

**Comment by vjeux** [comment]
The fact that it breaks is expected and I don't think that we should put a hack for it. However the new line is not.
