### ISSUE TITLE
ES7 support

### ISSUE THREAD

**Issue by mbrookes** [jlongster/prettier#69]
Adding this request as we are already using stage-2 through babel, and I notice that Chrome has supported ES7 features for some time now, so it would be good to get support in prettier, stage by stage. 🎭

**Comment by hzoo** [comment]
Kind of confused as to what this request means? Or you talking about the codebase itself or what prettier supports? It uses babylon as the parser and a fork of recast as the printer (supporting babylon) so it already supports anything Babel does.

**Comment by jlongster** [comment]
Yeah, lots of stuff like `do` expressions are already supported. We turn on all the plugins in babylon so everything it supports should parse. Basically we support whatever the latest parsers can parse.

**Comment by mbrookes** [comment]
Ah, right, thanks. Looks like it was flow-parser that was barfing on `static`. Apologies.

**Comment by hzoo** [comment]
Only issue for turning on everything by default is that if experimental proposals change need to figure out what to do (Babylon needs to as well) regarding versioning

**Comment by bakkot** [comment]
(To clarify, do-expressions are not an ES7 (i.e. ES2016) feature, nor will they be an ES2017 feature. They're not, yet, part of JavaScript at all.)
