### ISSUE TITLE
No links in changelog

### ISSUE THREAD

**Issue by darahak** [jlongster/prettier#701]
Hi there,

So I saw that [tweet](https://twitter.com/Vjeux/status/831350812412518400) and came to see what happened in the [changelog](https://github.com/jlongster/prettier/blob/master/CHANGELOG.md).
The thing is, the issues IDs are actually not links, so this is a little bit inconvenient to navigate through.

There are links when we go to the "Compare" page, but we also get all the commits, which can lead to too much information.

Maybe this is something that can be fixed with a tool? (if you're not already using one)

P.S.: I was waiting for some blocking issues to be fixed, but `0.17.0` might be the one. Thanks you all!

**Comment by vjeux** [comment]
The changelog right now is just a dump of all the commits... We should likely make a better changelog in the future but this is better for now that we are iterating very quickly on it.

**Comment by hzoo** [comment]
Also pretty simple to add, can make a PR

**Comment by darahak** [comment]
@hzoo Are you thinking about re-using what you have with Babel's changelog?

**Comment by jlongster** [comment]
You're supposed to click on the "link" in the changelog to get a real github commit range where you can click on all the links. The changelog is just a quick summary for now.

**Comment by jlongster** [comment]
We'll work on this more in the future, but in the effort of keeping our issues down, let's close this one for now.
