### ISSUE TITLE
Disable leading & for flow types

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#702]
```js
type ResponseMessage = MessageCommon & {
  messageType: 'RESPONSE',
  sequenceID: 'number',
};
```

turns into

```js
type ResponseMessage =
  & MessageCommon
  & {
    messageType: "RESPONSE",
    sequenceID: "number"
  };
```

which looks really weird. For `|`, they are usually chained so it feels nice, but you only have maximum one `&` so we should just display it inline like we do with #692

**Comment by houshuang** [comment]
I noticed this as well and thought at first it was a bit strange, but then got used to it. I agree that you usually only have one &, but is this a Flow rule or could

**Comment by vjeux** [comment]
@houshuang this is not a flow rule, but more of a usage pattern. & takes a subset of a type and | merges two types. So it's less likely you want to make a bigger type from two types than find the intersection of many types.
