### ISSUE TITLE
Removes new line at EOF when file has been reformatted

### ISSUE THREAD

**Issue by greggb** [jlongster/prettier#708]
Still seeing the behavior from https://github.com/jlongster/prettier/issues/55 and https://github.com/jlongster/prettier/pull/105

When formatting a file with the JSPrettier package in Sublime it removes the new line if any reformatting has been done. Looks they are using the latest version of prettier (https://github.com/jonlabelle/SublimeJsPrettier/blob/master/package.json).

Would this be specific to the plugin?

**Comment by vjeux** [comment]
https://packagecontrol.io/ is down so I can't install it right now, but it's likely an issue with the package.

**Comment by vjeux** [comment]
Note that this is using the globally installed version of prettier. If you do

```js
npm ls -g prettier
```

you can see what version it uses.

**Comment by greggb** [comment]
Looks like I'm using `prettier@0.17.1`. I'll do some more digging to see if I can repro without this package

**Comment by vjeux** [comment]
Thank you!

**Comment by vjeux** [comment]
If you can run `prettier file.js --write` and repro locally that would be useful as well.

**Comment by greggb** [comment]
You're absolutely right, running from the command line works fine, but repros with the package. Sorry for erroneous issue!

**Comment by vjeux** [comment]
Thanks for raising it, we need to make sure that the prettier integrations are of high quality, this is a big part of the experience :)
