### ISSUE TITLE
Option to preserve new lines by block or file

### ISSUE THREAD

**Issue by garth** [jlongster/prettier#709]
In some frameworks (eg [cerebral](http://www.cerebraljs.com/)) the layout of arrays and object literals is critical to readability (a selling point of the cerebral framework).

Normally formatted as follows, the code reads like a high level recipe.

```js
const loginSignal = [
  startSpinner,
  postLogin, {
    success: [
      updateCredentials,
      redirectHome
    ],
    error: [
      showError
    ]
  },
  stopSpinner
];
```

Prettier will reformat to the following:

```js
const loginSignal = [
  startSpinner,
  postLogin,
  {
    success: [updateCredentials, redirectHome],
    error: [showError]
  },
  stopSpinner
];
```

Maybe not critical in this simple example, but in longer code blocks the details can get lost, hindering readability.

If there were a way to flag that a file or block should have new lines preserved, maybe this would help these cases?

https://github.com/jlongster/prettier/pull/707

**Comment by vjeux** [comment]
Could you give an example where there are readability issues? This example looks fine to me being collapsed

**Comment by jlongster** [comment]
Yeah, it actually looks better collapsed in my opinion... You can read left-to-right what's happening when it's a short workflow.

**Comment by garth** [comment]
OK, will just have to get used it I guess and not other-think the formatting.
