### ISSUE TITLE
Last line comment is not stable

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#723]
```js
function f() {
  a
  /* eslint-disable */
}
```

turns into

```js
function f() {
  a;

  /* eslint-disable */
}
```

and back

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20a%5Cn%20%20%2F*%20eslint-disable%20*%2F%5Cn%7D%5Cn%5Cnfunction%20f()%20%7B%5Cn%20%20a%3B%5Cn%5Cn%20%20%2F*%20eslint-disable%20*%2F%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Originally reported by @alekhurst in #717

**Comment by alekhurst** [comment]
Thanks @vjeux, I didn't have time to do this today, but this is the exact bug I was facing!
