### ISSUE TITLE
Omits useful parenthesis

### ISSUE THREAD

**Issue by stunaz** [jlongster/prettier#729]
```javascript
    while((a==b && c==d) || (e==f || g==k)){

    }
```
outputs

```javascript
    while (a == b && c == d || (e == f || g == k)) {
    }
```

I have therefore this warning
`warning  Unexpected mix of '&&' and '||'  no-mixed-operators`

**Comment by callumlocke** [comment]
Why did you close this? Did you find a solution?

**Comment by azz** [comment]
Prettier no longer outputs code like that. It will now output:

```
while ((a == b && c == d) || (e == f || g == k)) {}
```

**Comment by caub** [comment]
Huh why? it's not eve configurable. I don't understand how those things gets changed suddenly, the previous behavior was totally fine, the expression is simple, and everyone knows well that `&&` has precendece over `||`

**Comment by lydell** [comment]
> everyone know well that `&&` has precedence over `||`, and comparison operators has precedence over them too

Everyone knows a lot of things.

**Comment by caub** [comment]
sure, I see the point, but in

```js
while ((a == b && c == d) || (e == f || g == k)) {}
```

the lack of `===` is much more concerning than the extraneous and noisy parentheses

**Comment by j-f1** [comment]
> the lack of `===` is much more concerning

If you type `===`, we’ll output `===`. If you type `==`, we’ll output `==`.

> At least have it configurable (the useless parentheses rule), that would be great

https://prettier.io/docs/en/option-philosophy.html

**Comment by caub** [comment]
Yes, prettier is opinionated, I've seen that, thanks, I'll try to deal with that case, since this tool has other great benefit otherwise
