### ISSUE TITLE
Same config different output with vscode plugin

### ISSUE THREAD

**Issue by dburles** [jlongster/prettier#731]
I've encountered a weird inconsistency between my editor and a git hook, yet they seemingly both have the same configuration. v0.18.0.

Config:

```
  "prettier.singleQuote": true,
  "prettier.trailingComma": true,
```

Editor: 

```
        requireTeamMeeting: (
          task.teamMeetingRiskLate ||
            task.teamMeetingInputRequired ||
            task.teamMeetingRiskLate ||
            task.teamMeetingWinInfo
        ),
```

Git hook or `node_modules/prettier/bin/prettier.js  --single-quote --trailing-comma imports/ui/containers/TaskListDueDate.js` results in:

```
        requireTeamMeeting: task.teamMeetingRiskLate ||
          task.teamMeetingInputRequired ||
          task.teamMeetingRiskLate ||
          task.teamMeetingWinInfo,
```

Any clue what might cause this?

**Comment by demoneaux** [comment]
The vscode plugin uses a bundled version of prettier by default, which is probably a different version from your npm module. There's already an issue for that: https://github.com/esbenp/prettier-vscode/issues/29. For now, you can wait for them to update the vscode plugin.

**Comment by dburles** [comment]
Ah, I had assumed it was just using prettier from `node_modules`. That makes sense. Thanks @demoneaux
