### ISSUE TITLE
Getting a really clear definition of what this actually is?

### ISSUE THREAD

**Issue by CrashyBang** [jlongster/prettier#77]
This is not a troll question I think I am genuinely missing something awesome here and I want to understand.

I notice you have made references back to eslint and how this _actually_ formats your code, for javascript I use vim with [vim-autoformat](https://github.com/Chiel92/vim-autoformat) and [XO](https://github.com/sindresorhus/xo#vim) (which is built on eslint similar to [standard](https://github.com/feross/standard) I believe).

What I am trying to understand is how **Prettier** differs from what I currently have? is it a more aggressive reformat? Can it do more?

Sorry I am just really trying to get a grasp of what is new.

Cheers.

**Comment by hzoo** [comment]
Less/no config, autofix for everything Babel supports (like babel-eslint), however only deals with styling unlike ESLint (a linter + autofixer), accounts for max-line-length automatically

**Comment by jlongster** [comment]
It's an alternative to enforcing style by configuring a lot of little "nits" in eslint, and instead just forcible re-printing everything. If you are using XO which is built on eslint, it's depending on eslint's `--fix` behavior which doesn't actually fix a wide array of style. For example the stricted eslint config I know happily passes all of these:

```js
foo({ num: 3 },
  1, 2)

foo(
  { num: 3 },
  1, 2)

foo(
  { num: 3 },
  1,
  2
)
```

Prettier always ensures that 100% of your code is formatted consistently. I hope you try it out, and it's fine if it's not for you!

**Comment by CrashyBang** [comment]
@jlongster thank you that is exactly what I was after :) And I will definitely be trying it!
