### ISSUE TITLE
Comments in between if, else-if and else blocks produces syntax error

### ISSUE THREAD

**Issue by stadelmanma** [jlongster/prettier#78]
It seems when there are in-line comments between if blocks the else or else-if line is drug up into the comments line resulting in a syntax error. This was produced by running `prettier` no additional options. 

```js
//
// checks the parent element for time range values or date values
function to_and_from_timestamps(parent) {
    var from_ts = '';
    var to_ts = '';
    var time_values = get_all_form_values(parent);
    //
    // getting time range data
    if (time_values.hasOwnProperty('time_range')) {
        from_ts = time_values['time_range'].split('|')[0] + ' 00:00:00';
        to_ts = time_values['time_range'].split('|')[1] + ' 23:59:59';
    }
    // using calendar inputs instead
    else {
        from_ts = '{st-year}-{st-month}-{st-day} 00:00:00'.format(time_values);
        to_ts = '{en-year}-{en-month}-{en-day} 23:59:59'.format(time_values);
    }
    //
    return { from_ts: from_ts, to_ts: to_ts };
}
```

becomes... 

```js
//
// checks the parent element for time range values or date values
function to_and_from_timestamps(parent) {
  var from_ts = "";
  var to_ts = "";
  var time_values = get_all_form_values(parent);
  //
  // getting time range data
  if (time_values.hasOwnProperty("time_range")) {
    from_ts = time_values["time_range"].split("|")[0] + " 00:00:00";
    to_ts = time_values["time_range"].split("|")[1] + " 23:59:59";
  }
  // using calendar inputs instead else {
    from_ts = "{st-year}-{st-month}-{st-day} 00:00:00".format(time_values);
    to_ts = "{en-year}-{en-month}-{en-day} 23:59:59".format(time_values);
  }
  //
  return { from_ts: from_ts, to_ts: to_ts };
}
```

**Comment by vjeux** [comment]
Repro case:

```js
if (true) {
  something();
  // something
}
// something
else {
  something();
}
```

which should be

```js
if (true) {
  something();
  // something
}
// something
 else {
  something();
}
```

In `printTrailingComment`, we need to have a way to say "always put a \n but don't add 2 if one was already there". I tried line, softline and hardline but doesn't work, it adds an empty line after when not needed.
https://github.com/jlongster/prettier/blob/master/src/comments.js#L269

**Comment by jlongster** [comment]
Yep, comments need a few fixes. I need to check out some of these cases. I don't fully follow your repro case @vjeux because the problem is the `// something else {` which I don't see?

**Comment by vjeux** [comment]
Sorry, the second block is what it **should** be, not what it currently prints

**Comment by vjeux** [comment]
Repro case:
https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22if%20(true)%20%7B%5Cn%20%20something()%3B%5Cn%20%20%2F%2F%20something%5Cn%7D%5Cn%2F%2F%20something%5Cnelse%20%7B%5Cn%20%20something()%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by rafayepes** [comment]
The problem seems to be with single line comments between if and else statements. Two more examples:

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22if%20(x)%20%7B%5Cn%20%20%20%20foo()%3B%5Cn%7D%5Cn%5Cn%2F%2F%20Problematic%20comment%5Cnelse%20%7B%5Cn%20%20%20%20bar()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22if%20(x)%20%7B%5Cn%20%20%20%20foo()%3B%5Cn%20%20%5Cn%7D%2F%2F%20Problematic%20comment%5Cnelse%20%7B%5Cn%20%20%5Cn%20%20%20%20bar()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by jlongster** [comment]
Thanks. Comments are going to be re-hauled this week and should be a lot more stable.

**Comment by jlongster** [comment]
See above PR

**Comment by jlongster** [comment]
See #487 as a follow-up, it no longer produces invalid code but we need to fix the formatting
