### ISSUE TITLE
Consistency: quoted/unquoted property names in object literals

### ISSUE THREAD

**Issue by bakkot** [jlongster/prettier#79]
Currently prettier gives different output for `({ a: 0 });` and `({ 'a': 0 });`. I would think they'd be the same. (Presumably this is because babylon represents these with different ASTs, but it probably shouldn't. Other parsers e.g. [shift](https://astexplorer.net/#/JTW9zuNVfJ) do not.)

Personally I'd prefer that the quotes are present only when necessary, and that numeric keys are normalized to match the key name they'll actually produce (which already happens).

Some examples of my preferred syntax:
`({ '': null });` -> `({ '': null });`
`({ a: null });` -> `({ a: null });`
`({ 'a': null });`-> `({ a: null });`
`({ ' a': null });` -> `({ ' a': null });`
`({ 100: null });` -> `({ 100: null });`
`({ '100': null });` -> `({ 100: null });`
`({ 1e2: null });` -> `({ 100: null });`
`({ '1e2': null });` -> `({ '1e2': null });`
`({ 0x64: null });` -> `({ 100: null });`
`({ '0x64': null });` -> `({ '0x64': null });`
`({ 100.0: null });` -> `({ 100: null });`
`({ 100.1: null });` -> `({ 100.1: null });`
`({ '100.0': null });` -> `({ '100.0': null });`

**Comment by marcialca** [comment]
Repro on [prettier-browser]( https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22(%7B%20''%3A%20null%20%7D)%3B%5Cn(%7B%20a%3A%20null%20%7D)%3B%5Cn(%7B%20'a'%3A%20null%20%7D)%3B%5Cn(%7B%20'%20a'%3A%20null%20%7D)%3B%5Cn(%7B%20100%3A%20null%20%7D)%3B%5Cn(%7B%20'100'%3A%20null%20%7D)%3B%5Cn(%7B%201e2%3A%20null%20%7D)%3B%5Cn(%7B%20'1e2'%3A%20null%20%7D)%3B%5Cn(%7B%200x64%3A%20null%20%7D)%3B%5Cn(%7B%20'0x64'%3A%20null%20%7D)%3B%5Cn(%7B%20100.0%3A%20null%20%7D)%3B%5Cn(%7B%20100.1%3A%20null%20%7D)%3B%5Cn(%7B%20'100.0'%3A%20null%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D)
