### ISSUE TITLE
Rundown #3 (JSX)

### ISSUE THREAD

**Issue by vramana** [jlongster/prettier#8]
Taking some inspiration from @vjeux. Here is rundown through the code base I am working on

- [x] Probably a space before />

![image](https://cloud.githubusercontent.com/assets/3112509/21739965/f63e7c80-d4cf-11e6-94d9-473d3a21e849.png)

- [ ] Prioritize breaking on JS props rather than prop value expressions
- [ ] Prioritize breaking on { of the prop value expression rather than arrow function arguments

![image](https://cloud.githubusercontent.com/assets/3112509/21739971/2725030a-d4d0-11e6-8e89-347ec7b284cb.png)
 
- [ ] Don't break on JSX child element and instead break at `=`

![image](https://cloud.githubusercontent.com/assets/3112509/21739976/49cd11ae-d4d0-11e6-87dd-9611ba65bfc6.png)

- [ ] ~~Should jscodefmt sort JSX props? I heard refmt does something like that. I haven't tried it yet.~~

- [ ] ~~Rewrite expression using ternary operator~~

![image](https://cloud.githubusercontent.com/assets/3112509/21740014/97f9e98c-d4d1-11e6-8876-df36f4293d2c.png)
 
- [ ] What should happen in this case? 😕 

![image](https://cloud.githubusercontent.com/assets/3112509/21740020/c06ed288-d4d1-11e6-8b93-9ea9d147f89d.png)

- [x] Leave blank line between class methods/properties

![image](https://cloud.githubusercontent.com/assets/3112509/21740041/5bf7ac7a-d4d2-11e6-9fe3-8c6b9db38412.png)

- [ ] ~~Probably a space before `(` for anonymous generator functions~~

![image](https://cloud.githubusercontent.com/assets/3112509/21740068/96932674-d4d3-11e6-9523-f35020ac908e.png)

**Comment by vjeux** [comment]
> Should jscodefmt sort JSX props? I heard refmt does something like that. I haven't tried it yet.

> Rewrite expression using ternary operator

Those are not safe operations to do in JavaScript. They may change the actual output of a program. So it's probably better to have a lint rule do them.

**Comment by vramana** [comment]
@vjeux Makes sense.

**Comment by jlongster** [comment]
> Probably a space before ( for anonymous generator functions

I don't think I want to do this. For consistency we'd have to put a space with anon functions too (`function (`) which starts to get annoying. I don't think `function*() { ... }` looks bad and is consistent. This is one of those things where once you see if a few times you'll think it looks fine.

**Comment by jlongster** [comment]
Good points, a few of them are already fixed on master from other comments, and the rest get into some difficult heuristics but it's worth seeing what we can do. I spent some time on JSX but there's definitely more things we could do.

I need to reduce the amount of time I'm working on this soon. I will slowly tweak thing over time but it'd be great if those who proposed changes could actually open PRs. I will write more docs soon about how the printer works to aid this.

**Comment by wmertens** [comment]
For the `...(foo && bar || meep)` case, at least insert parens: `...((foo && bar) || meep)`. Operator precedence is sometimes surprising.

**Comment by vramana** [comment]
I am closing this to reduce noise since people have filed individual issues for most of the issues listed here.
