### ISSUE TITLE
[tip] npm script to format a source folder

### ISSUE THREAD

**Issue by tnhu** [jlongster/prettier#80]
I've been jealous with golang's gofmt, until now! Thank you for making a great tool!

Here's npm script to format a whole src folder, if anyone is interested.

`$ npm i --save-dev prettier`

**package.json**

```
 "scripts": {
    "format": "for f in src/**/*.js; do ./node_modules/.bin/prettier $f --write --single-quote; done"
  }
```

`$ npm run format`

**Comment by vjeux** [comment]
You should use `xargs`, otherwise you are going to pay the price of loading all the JavaScript for every single file. The following should be way faster:

```
find src/ -name '*.js' | xargs ./bin/prettier.js --write
```

**Comment by tnhu** [comment]
xargs is actually a lot faster (6 seconds vs. 3 minutes against my local node_modules/). Thanks @vjeux!

**Comment by vramana** [comment]
Globs are supported now. We can close this issue.
