### ISSUE TITLE
Introducing prettier-browser

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#81]
It is very handy to be able to try things out in the browser instead of having to npm install locally.

Demo: https://vjeux.github.io/prettier-browser/
Source: https://github.com/vjeux/prettier-browser/

I think it would be awesome if it was part of core and shipped as part of the release process. In the meantime, I'm going to try and keeping it up to date.

**Comment by vramana** [comment]
Closing this issue in favour of PR #122 😛
