### ISSUE TITLE
Strips comments inside of empty if/else

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#87]
```js
if (1) {
  // Comment 1
} else {
  // Comment 2
}
```

after

```js
if (1) {}
else {}
```

https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22if%20(1)%20%7B%5Cn%20%20%2F%2F%20Comment%201%5Cn%7D%20else%20%7B%5Cn%20%20%2F%2F%20Comment%202%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Related: https://github.com/jlongster/prettier/issues/31

**Comment by jlongster** [comment]
Moved to #275
