### ISSUE TITLE
Boolean && should either always break or never break

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#89]
```js
function a() {
  switch(1) {
    case "Literal":
      return parent.type === "MemberExpression"
        && isNumber.check(node.value)
        && name === "object"
        && parent.object === node;
  }
}
```

output

```js
function a() {
  switch (1) {
    case "Literal":
      return parent.type === "MemberExpression" && isNumber.check(node.value) &&
        name === "object" &&
        parent.object === node;
  }
}
```

expected output

```js
function a() {
  switch (1) {
    case "Literal":
      return parent.type === "MemberExpression" &&
        isNumber.check(node.value) &&
        name === "object" &&
        parent.object === node;
  }
}
```

(or even better, add parenthesis)

```js
function a() {
  switch (1) {
    case "Literal":
      return (
        parent.type === "MemberExpression" &&
        isNumber.check(node.value) &&
        name === "object" &&
        parent.object === node
      );
  }
}
```

https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22function%20a()%20%7B%5Cn%20%20switch(1)%20%7B%5Cn%20%20%20%20case%20%5C%22Literal%5C%22%3A%5Cn%20%20%20%20%20%20return%20parent.type%20%3D%3D%3D%20%5C%22MemberExpression%5C%22%5Cn%20%20%20%20%20%20%20%20%26%26%20isNumber.check(node.value)%5Cn%20%20%20%20%20%20%20%20%26%26%20name%20%3D%3D%3D%20%5C%22object%5C%22%5Cn%20%20%20%20%20%20%20%20%26%26%20parent.object%20%3D%3D%3D%20node%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
I think this should be the behavior for all binary or logical operators, so a long (x + y + z + etc) chain would break as well. The difficultly will be what happens when mixing operators as I think it would look better it we tried to only break operators on the same precedence level. I'm playing with this now.
