### ISSUE TITLE
Prettifying components of React

### ISSUE THREAD

**Issue by aaronplanell** [jlongster/prettier#91]
Hi!

First of all, thanks a lot for your project. It will be very helpful :+1: 

But, if I have this piece of code of React:
```
        <SortableTree
          treeData={this.state.treeData} 
          onChange={treeData => this.setState({ treeData })}
        />
```

And I prettifier it, I get:
```
        <SortableTree treeData={this.state.treeData} onChange={
          treeData => this.setState({ treeData })
        } />
```

In my humble opinion, I think the first one is more readeable. What you think about it?

Best regards,
Aaron Planell

**Comment by ndelangen** [comment]
I find them both fine to be honest, but slightly agree more with the current implementation.

**Comment by vramana** [comment]
This is has been reported in other issues. You can close this one.

**Comment by aaronplanell** [comment]
Hi!

What a quick response :smile: . Maybe this other solution:
```
        <SortableTree
          treeData={this.state.treeData} 
          onChange={
	     treeData => this.setState({ treeData })
	  }
        />
```

It's a midpoint. I think it's important give more visibility to the onChange property. But, I must confess that I think you're right in marking in a different way the functions.

Thanks a lot!

**Comment by aaronplanell** [comment]
Hi @vramana! 

OK. I close the issue. 

Thanks for your work!
