### ISSUE TITLE
Prettier change all line break to LF

### ISSUE THREAD

**Issue by onemen** [jlongster/prettier#92]
I'm on windows 10, and all my line break are CRLF, after using Prettier all line break converted to LF.

Prettier should not change existing line break.

**Comment by wmertens** [comment]
Why do you want to ship your code with extra useless characters?

**Comment by jlongster** [comment]
I'm open to detecting if the first newline in the file is CRLF and using that. What does everyone else think?

**Comment by bakkot** [comment]
JavaScript linebreaks are canonically LF: that is, in a template literal, a literal CRLF sequence is converted to LF. So if someone working on a project of mine has put in a CRLF, it's definitely a formatting issue which something like prettier should fix. As such, I'm strongly in favor of the current behavior.

**Comment by cphoover** [comment]
is there not a configuration flag to specify "windows" or "unix" LBs?

**Comment by vjeux** [comment]
@cphoover prettier will respect the first end of line it sees. If it's a \r\n it's going to replace all the others with \r\n and same for \n.
