### ISSUE TITLE
Trying prettier in emacs give errors (OSX)

### ISSUE THREAD

**Issue by cedricpinson** [jlongster/prettier#99]
Here the error when trying to apply prettier on a buffer
```
prettier errors:
/Users/trigrou/.nvm/versions/node/v5.5.0/lib/node_modules/prettier/bin/prettier.js:4
const fs = require("fs");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

not sure exactly what's the problem

**Comment by vramana** [comment]
@cedricpinson Does calling prettier on the command line also give the same error? Can you try with a more recent version of node too?

**Comment by jlongster** [comment]
Yeah, that looks like a local problem with prettier, not emacs. We should support back to node 4 now. What version are you on? Make sure you update to 0.0.4 to get older node support.

**Comment by cedricpinson** [comment]
I did npm install -g prettier

/Users/trigrou/.nvm/versions/node/v5.5.0/bin/prettier -> /Users/trigrou/.nvm/versions/node/v5.5.0/lib/node_modules/prettier/bin/prettier.js
/Users/trigrou/.nvm/versions/node/v5.5.0/lib
└─┬ prettier@0.0.5
  ├── ast-types@0.9.3  (git+https://github.com/jlongster/ast-types.git#4b373d7e710105b07b22a12389ef2d8e1bcf2412)
  └── get-stdin@5.0.1

Actually it looks like emacs is using /usr/local/bin/node which is v0.12.7
and in a terminal command /Users/trigrou/.nvm/versions/node/v5.5.0/bin/node which is v5.5.0

**Comment by vramana** [comment]
Looks like that's an issue with your $PATH. Since this is not an issue related to prettier anymore, I am closing this issue.

**Comment by mlunoe** [comment]
If anybody is wondering I had a similar issue for Sublime Text 3 and ended up setting the project settings to be using the same node as the prettier was installed with:
```js
  "settings": {
    "js_prettier": {
      "prettier_cli_path": "/Users/ml/.nvm/versions/node/v4.4.4/bin/prettier",
      "node_path": "/Users/ml/.nvm/versions/node/v4.4.4/bin/node"
    }
  }
```

This was not super obvious to me when installed it and wanted to use it with my editor.
